/* BioHackathon 2026 — participant index.
   Extracted from "Copy of BH26 Self introduction slides" (slides 3-78 of 117).
   Each id is that person's SLIDE NUMBER in that deck — the photo workflow relies on it.
   Regenerate this file from the deck; the app reads nothing else.
   Fields: n name, a affiliation, c country, co coding, i interests, s skills, m message, t topic tags */
window.BH_SOURCE = {
  deck: 'https://docs.google.com/presentation/d/1UWasNu6Wa_zCRhuWErF0cu2-uHpxwVBOU_6bNarQe1c/edit',
  slidesRead: '3–78 of 117'
};
window.BH_PEOPLE = [
  { id: 'p3', n: 'Toshiaki Katayama', a: 'DBCLS / BSI, NIG', c: 'Japan', co: ['Ruby', 'JavaScript', 'SPARQL'],
    i: 'Design & develop open source tools for knowledge graphs and genome graphs. TogoPackage and TogoMCP give AI agents access to local data and public life-science databases. Wants Japan to come together to design its new national bioscience database center.',
    s: 'Facilitates discussions, coding, and drinking :)',
    m: 'Started learning the tenor saxophone this year. Tasted sake from 670+ breweries across Japan — brought 20+ bottles of Ehime local sake.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Databases', 'Genomics'] },
  { id: 'p4', n: 'Susumu Goto', a: 'DBCLS', c: 'Japan', co: ['Perl', 'R'],
    i: 'KEGG and LinkDB at Kyoto University until 2017; since then database integration via knowledge graphs, jPOST proteome database, and NLP/LLM for biological literature mining.',
    s: 'Database integration; proteome data, pathway and reaction data',
    m: 'Mainly in charge of management rather than coding now, but would like to discuss database integration. Member of the male choir Tokyo Lietertafel 1925.',
    t: ['Knowledge graphs', 'Databases', 'Proteomics', 'Text mining', 'LLM/AI'] },
  { id: 'p5', n: 'Shuichi Kawashima', a: 'DBCLS', c: 'Japan', co: ['Ruby'],
    i: 'KEGG, MAGEST, AAindex; Togo* products; RDF portal; TogoMedium and the Growth Medium Ontology. Integration of microorganism-related information.',
    s: 'Data integration, RDF/OWL/SPARQL, data models, web services, triple stores, Ruby, Togo* tools',
    m: "Since the Covid19 pandemic, I've spent more time cooking. Octopus eggs.",
    t: ['RDF/SPARQL', 'Ontologies', 'Databases', 'Microbiology', 'FAIR/Standards'] },
  { id: 'p6', n: 'Toyofumi Fujiwara', a: 'DBCLS', c: 'Japan', co: [],
    i: 'AI-based diagnostic support tools — DiseaseSearch, PanelSearch, CaseSharing. Enhancing interoperability between Japanese and international disease resources: NanbyoData, NANDO, Mondo Japanese.',
    s: 'Rare disease data curation and interoperability; biomedical informatics and knowledge representation',
    m: 'We will be developing a diagnostic support tool using LLMs, so if you are interested, look for this doll — ZebraSeek-kun.',
    t: ['Rare disease', 'LLM/AI', 'Ontologies', 'Clinical', 'FAIR/Standards'] },
  { id: 'p7', n: 'Mari T. Minowa', a: 'DBCLS', c: 'Japan', co: ['???'],
    i: 'Evolution of colicins, expression of human blood factors, promoter analysis of dopamine receptor genes, glycosyl transferases. Launch and operation of the NBDC human database from the ethical and personal-information viewpoint.',
    s: 'Knowledge to take charge of various aspects around the research (public relations, contracts, help desk)',
    m: "I'm still caught up in the Kawagoe festival. Love butterflies and grow many plants. Love dinos.",
    t: ['Databases', 'Clinical', 'Glycomics'] },
  { id: 'p8', n: 'Yuki Moriya', a: 'DBCLS / BSI, NIG', c: 'Japan', co: ['JavaScript', 'SPARQL', 'Perl'],
    i: 'Web tools for the semantic web — SPARQL support, Endpoint browser, SPARQList. Data visualization: Protein browser, Haplotype explorer. Data integration: TogoDX/human, Togo*, DIVE. jPOST, LLMs.',
    s: 'SPARQL, SPARQList and TogoStanza',
    m: 'The organizers prepared Japanese sake from Aichi for this BH.',
    t: ['RDF/SPARQL', 'Visualisation', 'Variants', 'Proteomics', 'Web dev'] },
  { id: 'p9', n: 'Yasunori Yamamoto', a: 'DBCLS', c: 'Japan', co: ['Perl', 'Python', 'Java', 'SPARQL', 'JavaScript', 'C#'],
    i: 'Services related to literature — Allie, inMeXes. Semantic web / AI: TogoMCP, Umaka-YummyData, Umaka Viewer, JSON2LD Mapper, RDF-doctor, TogoPics. Plans: making RDF data more reliable and connectable; extracting accession numbers from literature.',
    s: 'Anything related to LLM, RDF, OWL, ShEx, SPARQL, and MCP. Current interest is data quality and MCP for DBs.',
    m: 'I love onsen / spa. Taking a long walk. Walking with a dog.',
    t: ['RDF/SPARQL', 'LLM/AI', 'Text mining', 'FAIR/Standards', 'Ontologies'] },
  { id: 'p10', n: 'Hirokazu Chiba', a: 'DBCLS', c: 'Japan', co: ['Perl', 'Python', 'JavaScript', 'C'],
    i: 'Comparative genomics across model organisms and ~1,000 bacteria/archaea. Semantic web and graph DBs, Orthology Ontology, SPARQL tooling (spang, formatter), PG format for property graphs, RAG systems over biomedical databases.',
    s: 'RDF, SPARQL, JavaScript, Python, LLMs',
    m: 'Prefectures I have lived in: Ibaraki, Tokyo, Aichi, Chiba, Ibaraki again.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'Ontologies', 'Genomics', 'LLM/AI'] },
  { id: 'p11', n: 'Masae Hosoda', a: 'DBCLS', c: 'Japan', co: ['Python', 'Java', 'Ruby'],
    i: 'Multiple glycan structure alignment (MCAW tool), glycan-glycan binding molecules, Human Glycome Atlas. Linking Japanese intractable and rare disease information with glycan-related data. GlyCosmos: glycan motifs and MCP adoption.',
    s: 'Glycoinformatics. Learning SPARQL and RDF.',
    m: 'I will join the BioHackathon from September 17, as I will be attending a glycoscience conference beforehand.',
    t: ['Glycomics', 'Rare disease', 'RDF/SPARQL', 'Databases'] },
  { id: 'p12', n: 'Shuya Ikeda', a: 'DBCLS', c: 'Japan', co: ['awk'],
    i: 'TogoID — ID conversion service for life-science databases. BioSample curation. Improving metadata quality using LLMs.',
    s: 'Database integration (RDF, SPARQL); LLMs',
    m: 'I like spiders. I recently started bird watching.',
    t: ['Databases', 'LLM/AI', 'RDF/SPARQL', 'FAIR/Standards'] },
  { id: 'p13', n: 'Nobutaka Mitsuhashi', a: 'DBCLS', c: 'Japan', co: ['JavaScript', 'Bash', 'Python', 'CWL'],
    i: 'BodyParts3D; NBDC Human Database and its security guidelines; TogoVar — Japanese genetic variation, allele frequencies, clinical significance, pathogenicity prediction, literature integration, GWAS Catalog, structural variants from JoGo, LD from BioBank Japan.',
    s: 'Data integration through web application development using RDF middleware (SPARQList, Stanza); system administration of DBCLS computational infrastructure',
    m: 'I started using a dietary log app. I realized I was eating too much fat and salt, and not getting enough protein and vitamins. Data visualization is very useful.',
    t: ['Variants', 'Genomics', 'RDF/SPARQL', 'Web dev', 'Cloud/HPC'] },
  { id: 'p14', n: 'Keiko Sakuma', a: 'DBCLS', c: 'Japan', co: [],
    i: 'Research support staff; TogoTV support.',
    s: "I'm at the help desk with Mari and Terue. If you have any questions or problems, please contact the help desk.",
    m: 'No changes from BH24, but get older :) I like 🍵🧘',
    t: ['Databases'] },
  { id: 'p15', n: 'Tazro Ohta', a: 'Chiba University', c: 'Japan', co: ['Zed Agent x Claude'],
    i: 'Omics database (ChIP-Atlas), LLM-assisted data curation, Workflow-as-a-Service (Sapporo), workflow security risk assessment (Porkchop), Asian Biobank Assemble, and a new ultra-long-term data preservation project — preserving data for over five millennia.',
    s: 'Code. Food. Football. Explaining to a 4-year-old girl why she cannot do that in public.',
    m: 'Recent vibe coding practice made a Kanji practice app for kids. Moved to a riverside district in Tokyo. Became a Subaru owner.',
    t: ['Workflows', 'LLM/AI', 'Databases', 'Cloud/HPC', 'FAIR/Standards'] },
  { id: 'p16', n: 'Erick Antezana', a: 'United Nations — International Computing Center', c: 'Spain', co: ['Perl', 'Shell', 'Python', 'SPARQL', 'C', 'PowerPoint'],
    i: 'Semantic Systems Biology, agri-semantics, data governance. Semantic querying over agricultural ontologies, SDG-aligned knowledge representation using SDGIO, conversational interfaces, SPARQL-driven reasoning with explainable outputs.',
    s: 'Agro-chemical data management, semantic web, plant-related ontologies, data governance, data quality, FAIR',
    m: 'Born on 29 February, thus most probably the youngest participant. My first BioHackathon was 2010 in Tokyo.',
    t: ['Ontologies', 'RDF/SPARQL', 'Plants/Agriculture', 'FAIR/Standards'] },
  { id: 'p17', n: 'Mohammed S Mustak', a: 'Mangalore University', c: 'India', co: ['JavaScript'],
    i: 'Professor in genomics working on population genomics and evolutionary biology. Identified the founder population of the Lakshadweep islands and studied the population structure of tribal and Konkani populations of Karnataka. Interested in developing a pangenomic project for the Indian population.',
    s: 'Molecular biology, population genetics, bioinformatics, learning LLM',
    m: '',
    t: ['Population genetics', 'Genomics', 'Pangenome', 'Machine learning'] },
  { id: 'p18', n: 'Evan Bolton', a: 'NCBI', c: 'USA', co: ['Perl', 'C++', 'SPARQL', 'SQL'],
    i: 'PubChem and PubChemRDF since 2004. Connecting scientific information between chemical substances, biological targets and diseases. Exploring local LLMs to improve information quality, generate queries from natural language, and work more efficiently.',
    s: 'PubChem, NCBI resources, data integration, standards, RDF, cheminformatics, glycoinformatics, literature and patent informatics, machine readability, linked data, knowledge graphs',
    m: "Come see me and let's chat about your use cases, data needs and wants. How can I help you?",
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Databases', 'FAIR/Standards'] },
  { id: 'p19', n: 'Orion Buske', a: 'PhenoTips', c: 'Canada', co: ['Python', 'JavaScript', 'Shell', 'Cursor'],
    i: 'Running a startup building medical genetics software. AI in medical genetics workflows, especially family history and phenotype data. Standards: GA4GH, HPO, Phenopacket. Rare disease diagnosis and patient matchmaking — Matchmaker Exchange, PhenomeCentral, semantic similarity between patients.',
    s: 'Entrepreneurship and startups; somewhat rusty full-stack development; loves data analysis and visualization',
    m: 'Highly food-motivated. Loves hiking, canoe camping, foraging mushrooms. Maitake!',
    t: ['Rare disease', 'Clinical', 'FAIR/Standards', 'LLM/AI', 'Visualisation'] },
  { id: 'p20', n: 'Michel Dumontier', a: 'Maastricht University', c: 'Netherlands', co: ['Python', 'agentic coding'],
    i: 'Biochemist by training, data scientist by practice. FAIR data, open science, reproducibility. Ontologies (SIO, SULO), RDF linked data (Bio2RDF), data standards (HCLS dataset description), KG metadata and schema. Neurosymbolic AI: biomedical embeddings, ontology mappings, reasoner agents, drug discovery and personalized medicine. Plans: a Biomedical Research Assistant multi-agent system.',
    s: 'Ontologies, linked data, data standards, neurosymbolic AI',
    m: 'Temper unbridled enthusiasm with focused effort to give shape to the life you imagine.',
    t: ['Ontologies', 'Knowledge graphs', 'FAIR/Standards', 'LLM/AI', 'Machine learning'] },
  { id: 'p21', n: 'Dorothy Ellis', a: 'RIKEN IMS, Yokohama', c: 'Japan', co: ['R', 'C++', 'Python', 'Nextflow'],
    i: 'Data analysis with omics data — mostly transcriptomics and epigenomics, slowly more genomics. Develops machine learning models, mainly NMF-based. Interested in reproducibility, parameter tuning for unsupervised models, graph regularization, clustering, dimension reduction.',
    s: 'Statistics, R coding, data analysis and unsupervised learning',
    m: 'Used to sing in a metal band (would want to do it again). Row in my free time. Trying to get back into running.',
    t: ['Machine learning', 'Genomics', 'Workflows'] },
  { id: 'p22', n: 'Vincent Emonet', a: 'Swiss Institute of Bioinformatics', c: 'Switzerland', co: ['Rust', 'Python', 'JavaScript'],
    i: 'Building systems to improve access to knowledge — knowledge graphs (ontology, RDF, SPARQL, nanopublications), FAIR data, LLM integration (MCP, agents). Recent work: production-ready LLM-assisted natural language to SPARQL, a language server for SPARQL, a Rust crate to interact with LLMs.',
    s: 'Building reusable packages and web services in various languages; contributing to other people’s code (if decently structured and documented)',
    m: 'First time here, but no stranger to hackathons. I love raw food, karaokes, and sake.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Web dev', 'FAIR/Standards'] },
  { id: 'p23', n: 'Takatomo Fujisawa', a: 'DDBJ, NIG', c: 'Japan', co: ['Perl', 'Ruby', 'SPARQL'],
    i: 'Oversees development and operation of all DDBJ databases and services — assembled sequences, SRA/GEA, BioProject/BioSample, MetaboBank, JGA. Applying AI/LLM to database repositories; advancing the RDF Portal with dynamic ID relationships and tools such as Bio-MCP-blast.',
    s: 'Repository development, database integration, genome annotation, curation',
    m: 'A lightning strike directly hit our institute and caused a power outage; the recovery work last week was quite tough. My photo was taken this summer when I climbed Mt. Rishiri in Hokkaido, wearing a BioHackathon tenugui.',
    t: ['Databases', 'LLM/AI', 'RDF/SPARQL', 'Genomics', 'FAIR/Standards'] },
  { id: 'p24', n: 'Chiharu Fujita', a: 'Hiroshima University', c: 'Japan', co: ['Shell'],
    i: 'Undergraduate student working on a meta-analysis comparing transposable elements in Aspergillus species using sequence data collected from public databases.',
    s: '',
    m: 'This is my first time participating in such an event. Although I am still gaining skills and knowledge, I am here to learn and to connect with people from diverse backgrounds. I enjoy tasting different kinds of sake.',
    t: ['Genomics', 'Microbiology'] },
  { id: 'p25', n: 'Airu Hayashi', a: 'Hiroshima University', c: 'Japan', co: ['Python', 'Shell'],
    i: 'Undergraduate student working on a meta-analysis of human transcriptome data related to stomach cancer collected from public databases.',
    s: '',
    m: "This is my first time participating in such an event. Although my skills and knowledge are still limited, I'll do my best and learn through this event.",
    t: ['Genomics', 'Machine learning'] },
  { id: 'p26', n: 'Naohisa Goto', a: 'The University of Osaka', c: 'Japan', co: ['Ruby', 'C', 'C++', 'R', 'Perl', 'PHP', 'Python'],
    i: 'Lecturer in the NGS Core Facility. Computer system administration, BioRuby since 2001, development of the Ruby language since 2011, genome/metagenome sequence analysis, gene expression analysis.',
    s: 'Programming, bioinformatics data analysis, server/network management. Interested in RDF and CWL.',
    m: 'I like travelling by train.',
    t: ['Genomics', 'Cloud/HPC', 'Workflows', 'Microbiology'] },
  { id: 'p27', n: 'Chihiro Higuchi', a: 'NIBN', c: 'Japan', co: ['R', 'vibe coding'],
    i: 'Building life-science information databases. Feature extraction with random forests and lasso. Metabolomics database. GWAS of Brugada syndrome. RDFization of NIBN-derived data. Local LLMs for analysis of personal information. Japanese food ontology — the purpose of this hackathon.',
    s: 'The Linux environment of the late 1990s; deployment of local LLM systems using Ollama',
    m: "I'm afraid I have to leave on Tuesday afternoon. I've learned that publishing a preprint can attract predatory journals. Won at an AI hackathon and a quantum ideathon.",
    t: ['Metabolomics', 'Ontologies', 'LLM/AI', 'Machine learning', 'Databases'] },
  { id: 'p28', n: 'Robert Hoehndorf', a: 'KAUST', c: 'Saudi Arabia', co: ['Groovy', 'C', 'C++', 'Aider'],
    i: 'Mostly interested in logic, knowledge representation, reasoning, and how to get machines to think better than humans. This year: structural variation and rare disease, a "vibe bioinformatics" system, LLM for OWL + SPARQL based on Vincent’s work.',
    s: 'Ontologies and knowledge-based methods; complex systems, networks, graphs',
    m: 'I developed an interest in birding in recent years. I observed a shoebill stork last month. Please join me for a birding expedition around the hackathon venue.',
    t: ['Ontologies', 'Knowledge graphs', 'LLM/AI', 'Rare disease', 'Variants'] },
  { id: 'p29', n: 'Tzung-Chien Hsieh', a: 'University Hospital Bonn', c: 'Germany', co: ['Python', 'Ruby'],
    i: 'Computational phenotyping of rare genetic disorders. GestaltMatcher — a deep learning framework for diagnosing rare disorders through facial image analysis — and the GestaltMatcher Database. Extending to brain MRI and fetal ultrasound imaging.',
    s: 'Facial image analysis and computer vision; exome and genomic data analysis; multimodal data integration',
    m: 'I am visiting Japan while my wife is taking care of our two-year-old daughter alone. So I have to fill two empty suitcases before I fly back to Germany. Looking for recommendations.',
    t: ['Rare disease', 'Machine learning', 'Clinical', 'Genomics'] },
  { id: 'p30', n: 'Manabu Ishii', a: 'Genome Analytics Japan', c: 'Japan', co: ['Z80', 'C', 'C++', 'Python', 'Perl', 'Java', 'JavaScript', 'CWL'],
    i: '20th-century software engineer. This BioHackathon: IHIW19 database development, and Trusted Research Environment if possible.',
    s: "I'm interested in coding with LLM and TDD",
    m: 'Yesterday I went to Expo25 and Expo70. This year I drank Pilsner Urquell in Plzeň and at Expo25. Went to four football matches.',
    t: ['Databases', 'LLM/AI', 'Clinical', 'Workflows'] },
  { id: 'p31', n: 'Priscilla Joanne', a: 'University of Tokyo', c: 'Japan', co: ['Python', 'SPARQL'],
    i: "Master's student in computational biology, in the Goto lab at DBCLS. Generating question-answer datasets using knowledge graphs from the RDF portal.",
    s: "I'm still new in the field, but in this BioHackathon I want to find practical advice, solidify my Master's topic, and listen to new things about research.",
    m: 'If you like specialty coffee and would like to explore the flavors of Indonesian coffee, contact me — my family runs a coffee business in Indonesia.',
    t: ['Knowledge graphs', 'LLM/AI', 'RDF/SPARQL'] },
  { id: 'p32', n: 'Mayumi Kamada', a: 'Kitasato University', c: 'Japan', co: ['Python', 'R', 'Ruby', 'JavaScript'],
    i: 'Genome assembly of Bacillus subtilis natto; clinical genome analysis, especially cancer; the MGeND disease variant database; molecular dynamics on K and Fugaku. Now: clinical (EHR, RWD) and disease genome analysis, structural variant comparison, personality traits and genome, multimodal data integration for drug development.',
    s: 'Machine learning models and three-dimensional structural analysis to predict the disease relevance of genomic variants; databases for genomic medicine',
    m: 'The happiest thing is drinking a highball.',
    t: ['Variants', 'Clinical', 'Machine learning', 'Structural biology', 'Databases'] },
  { id: 'p33', n: 'Hiromi Kajiya-Kanegae', a: 'NARO Institute of Crop Science', c: 'Japan', co: ['R', 'Python'],
    i: 'Pedigree Finder — a viewer for knowledge graphs of crop pedigrees, including rice for sake brewing — and the Pedigree Finder Ontology. At NARO, developing a tool to enhance interoperability of genetic-resource trait data between Japan and France, and localizing ontologies into Japanese using LLM.',
    s: 'Pedigree data, knowledge graphs of crops, data integration',
    m: 'I love sweets. I am interested in the use of knowledge graphs in agriculture.',
    t: ['Plants/Agriculture', 'Knowledge graphs', 'Ontologies', 'Visualisation'] },
  { id: 'p34', n: 'Alex Kanitz', a: 'University of Basel / Pacific Analytics Consulting', c: 'Switzerland', co: [],
    i: 'Open standards-based data analytics platforms with data and compute federation, AI support, tokenization — BioHackCloud, ELIXIR On Cloud, UniVerse Platform. Previously bioinformatics tool and workflow development, and before that RNA biology.',
    s: 'Web dev, GA4GH APIs, workflows, a bit of RO-Crate, a bit of DevOps',
    m: 'Since January 2025 I get up very early, because I started a job in one country while still living in another. Thanks to Manabu-san, last week I helped carry my first 神輿.',
    t: ['Workflows', 'Cloud/HPC', 'FAIR/Standards', 'Web dev'] },
  { id: 'p35', n: 'Yosuke Kawai', a: 'National Institute of Global Health Medicine', c: 'Japan', co: ['Python', 'R'],
    i: 'Molecular evolution, population genetics, human evolution, medical genomics, MGeND. Projects: pangenome graph focusing on structural variation — published the Japan-Saudi Pangenome with Robert, Maxat and Toshiaki — and an immunogenetics database; hosting IHIW19.',
    s: 'Genomic data analysis in the background of population genetics; large-scale analysis of genomic data on cluster computers',
    m: 'I have two cats.',
    t: ['Pangenome', 'Population genetics', 'Variants', 'Genomics', 'Cloud/HPC'] },
  { id: 'p36', n: 'Julia Koblitz', a: 'Leibniz Institute DSMZ', c: 'Germany', co: ['Python', 'PHP', 'JavaScript', 'SQL', 'MongoDB'],
    i: 'Head of Data Integration at DSMZ Digital Diversity.',
    s: 'Database and web development, data integration (e.g. via RDF), UI/UX and graphic design, artificial intelligence',
    m: 'I co-founded a startup that provides open source software for institutes to manage their research. I am still collecting Goshuin.',
    t: ['Databases', 'Web dev', 'RDF/SPARQL', 'Microbiology', 'Visualisation'] },
  { id: 'p37', n: 'Hyeokjin Kwon', a: 'University of Potsdam', c: 'Germany', co: ['C', 'Perl', 'Python', 'Rust'],
    i: 'PhD candidate; previously research data management engineering at TU Eindhoven and TU Delft. Interests: RDF, SPARQL, JSON-LD, OWL, CWL, large-scale data analysis workflows, workflow management systems (especially Snakemake), research software engineering.',
    s: 'Rusty and outdated experience with everything listed above. Here to polish my semantic web skills, explore DBCLS use cases, and find clues for my PhD topic.',
    m: 'In Korea, men can enroll in women’s universities for a master’s. One ancestry test says I’m 1% Japanese, so technically I belong here.',
    t: ['Workflows', 'RDF/SPARQL', 'FAIR/Standards', 'Ontologies'] },
  { id: 'p38', n: 'Jose Emilio Labra Gayo', a: 'University of Oviedo', c: 'Spain', co: ['Rust', 'Scala', 'Python'],
    i: 'Full professor and main researcher at WESO Lab. Co-author of Knowledge Graphs and Validating RDF Data. Maintains shapes-related libraries: rdfshape in Scala, and now rudof in Rust.',
    s: 'RDF and RDF 1.2, SPARQL, RDF data modeling and visualization (ShEx, SHACL, DCTAP), conversion between techniques, Rust/Scala/Python bindings. Started to learn about MCP servers.',
    m: "Punk-rock drummer in the 90s. Now I enjoy walking my dog.",
    t: ['RDF/SPARQL', 'Knowledge graphs', 'FAIR/Standards', 'Ontologies'] },
  { id: 'p39', n: 'Shuto Machida', a: 'Kyushu University', c: 'Japan', co: ['Python', 'Shell'],
    i: 'Developing haplotype phasing algorithms for the human genome; applying combinatorial optimization to genomic problems. Member of the JoGo project, building high-resolution haplotype reference panels from long-read sequencing data.',
    s: 'Combinatorial optimization, mathematical thinking, exploring IGV and VCF files, applying machine learning to research, interested in quantum computing applications',
    m: '3rd-year PhD student from Okinawa, MSc in mathematics (representation theory). Excited to finally explore Mie.',
    t: ['Variants', 'Genomics', 'Pangenome', 'Machine learning'] },
  { id: 'p41', n: 'Raúl Nicolás Mateos', a: 'National Cancer Center Research Institute', c: 'Japan', co: ['R', 'Python', 'Shell'],
    i: 'PhD in computational biology and medical sciences. Main interests are pangenomics and proteomics; previous work on methylation analysis, splicing junctions and spatial transcriptomics. Recently published on splicing junctions for detecting altered activation of the KEAP1-NRF2 pathway.',
    s: 'Multi-omics data analysis. Outside research: generative art, sewing, origami.',
    m: 'I always feel I may know a bit of many things but am not proficient enough at any, so I am really excited to learn from all of you.',
    t: ['Pangenome', 'Proteomics', 'Genomics', 'Machine learning'] },
  { id: 'p42', n: 'Masaaki Matsubara', a: 'The Noguchi Institute', c: 'Japan', co: ['Java'],
    i: 'Glycoinformatics. Main developer of WURCS, a glycan text format for integrating glycan-related databases. Developing algorithms to extract monosaccharides from chemical compounds; mass spectrometry data analysis for glycomics.',
    s: 'Glycoinformatics; cheminformatics, molecular simulation (MO, MM, MD)',
    m: 'Lately I have been into disentanglement puzzles (知恵の輪). I brought some with me today — if you want to try them, let me know.',
    t: ['Glycomics', 'Structural biology', 'Databases'] },
  { id: 'p43', n: 'Mkkm Chipo Ruhwode', a: 'Kitasato University, Faculty of Frontier Engineering', c: 'Japan', co: [],
    i: 'Graduated at the University of Zimbabwe in 2023 with an undergraduate degree in Statistics; research student at Kyoto University in 2025; now a first-year Master\u2019s student in bioinformatics at Kitasato University. Interests: bioinformatics, breast cancer research, and the application of computer science to medical data.',
    s: 'Statistics. Interested in coding. Since it is my first time here, I am looking forward to gaining practical skills in integrating biological datasets that I can apply to my breast cancer research.',
    m: 'I am an easy going person, I enjoy interacting with people. I knit very well if I am not lazy about it.',
    t: ['Machine learning', 'Clinical', 'Genomics'] },
  { id: 'p44', n: 'Miguel Mazumder', a: 'GaLSIC, Soka University', c: 'Japan', co: ['MATLAB', 'Python', 'Rust', 'Shell'],
    i: 'Human Glycome Atlas TOHSA — secure full-stack service for biodata with access control, data privacy and interoperability. NIH Common Fund Data Ecosystem: integration of n-triples/XML biomedical data with Neo4j and Cypher. Machine learning workflows and MATLAB image analysis pipelines. Interested in RDF data modeling, SPARQL, glycan data integration and ontology mapping.',
    s: 'Image processing and analysis, machine learning, Docker, NGS data analysis, knowledge graphs, computer vision',
    m: 'I can fall asleep anywhere. This is my first biohackathon and I am relatively new to semantic web technologies, so I hope to learn a lot here.',
    t: ['Glycomics', 'Knowledge graphs', 'Machine learning', 'RDF/SPARQL', 'Web dev'] },
  { id: 'p45', n: 'Gos Micklem', a: 'DBCLS / University of Cambridge', c: 'UK', co: ['Perl', 'Python', 'C'],
    i: 'PI of the InterMine project — HumanMine and FlyMine. Moving the back end from Postgres to QLever; wants BlueGenes to work on any SPARQL endpoint, e.g. the RDF portal. This time: infer the schema of a QLever endpoint into the InterMine model, and MetaStanza to InterMine.',
    s: 'Large-scale data integration and tools and interfaces for flexible, efficient querying and data visualisation',
    m: 'I metabolise caffeine very slowly and alcohol quite quickly.',
    t: ['Databases', 'RDF/SPARQL', 'Web dev', 'Visualisation', 'Knowledge graphs'] },
  { id: 'p46', n: 'Hiroyuki Mishima', a: 'Nagasaki University', c: 'Japan', co: ['Ruby', 'JavaScript', 'Python', 'R'],
    i: 'Assistant professor in rare disease bioinformatics; formerly dentist and post-doc in cleft palate and rare disease genetics. This hackathon: next-generation phenotyping by integrating facial analysis (GestaltMatcher) and HPO-based analysis (PubCaseFinder) to fight the diagnostic odyssey.',
    s: 'Full-stack bioinformatics from server room construction to building diagnostic workflows',
    m: '',
    t: ['Rare disease', 'Clinical', 'Workflows', 'Cloud/HPC'] },
  { id: 'p47', n: 'Masao Nagasaki', a: 'Kyushu University, Medical Institute of Bioregulation', c: 'Japan', co: ['Python', 'Java', 'Perl', 'Shell', 'R', 'SQL', 'PHP'],
    i: 'Professor, Division of Biomedical Information Analysis. Bioinformatics, medical informatics, genome biology, large-scale data analysis. Interests: ACTG-haplotype centric human data analysis, tool development and annotation; collaboration on haplotype-based analysis; haplotype-based semi-automatic annotation with database MCP; graph genome and T2T.',
    s: 'Haplotype analysis, tool development, annotation, large-scale data analysis',
    m: 'Welcome: post-doctoral fellow position available.',
    t: ['Variants', 'Pangenome', 'Genomics', 'Cloud/HPC', 'LLM/AI'] },
  { id: 'p48', n: 'Takeru Nakazato', a: 'NITE Biological Resource Center (NBRC)', c: 'Japan', co: ['Perl', 'Python'],
    i: 'NBRC provides bacteria and fungi as a bioresource center. POMIC — a catalog of microorganisms that utilize CO2. Interested in linking data across microbial culture collections and databases.',
    s: 'Databases; NGS analysis and gene expression analysis',
    m: 'Biodiversity information standards (TDWG) member — GBIF, BOLD, Catalogue of Life. I brought a net to catch insects.',
    t: ['Microbiology', 'Databases', 'Biodiversity', 'FAIR/Standards'] },
  { id: 'p49', n: 'Javier Millan Acosta', a: 'Maastricht University', c: 'Netherlands', co: ['Python', 'JavaScript', 'Shell', 'R', 'Java', 'Groovy'],
    i: 'PhD candidate developing and maintaining chemical and biomedical ontologies and tools for querying and visualizing them.',
    s: 'Ontologies and knowledge representation; pathways and toxicology modelling; data integration — RDF, SPARQL, shapes, modelling and tooling; Python web frameworks; packaging, dockerizing, GitHub actions, release management',
    m: 'Proudly tried fugu sashimi for the first time this week. First BH Japan. Co-leading a project for the upcoming ELIXIR BH about shapes and queries.',
    t: ['Ontologies', 'RDF/SPARQL', 'Visualisation', 'Web dev', 'FAIR/Standards'] },
  { id: 'p50', n: 'Claude Nanjo', a: 'University of Utah', c: 'USA', co: ['Java', 'Python', 'Kotlin', 'Rust'],
    i: 'Medical informatician focusing on clinical knowledge representation and applications of AI in medicine. Many years in health IT interoperability; HL7 CIMI and LHS co-chair. Currently focused on structured knowledge in agentic AI to improve clinical accuracy — agentic RAG using knowledge graphs, and fetching relevant patient data deterministically.',
    s: 'I would be very interested in how you leverage structured knowledge and deterministic workflows in your agentic AI.',
    m: 'I am learning my 11th (human) language.',
    t: ['Clinical', 'Knowledge graphs', 'LLM/AI', 'FAIR/Standards', 'Ontologies'] },
  { id: 'p51', n: 'Russell Neches', a: 'Kyoto University', c: 'Japan', co: ['Python', 'C'],
    i: '',
    s: '',
    m: 'Open source, open data, open science, open hardware — open all the things! Goal for the year: justify spending on fancy pens and inks. This is my second Biohackathon. I am on my fourth attempt to pass the driver license practical test.',
    t: ['Microbiology', 'Biodiversity'] },
  { id: 'p52', n: 'Kozo Nishida', a: 'RIKEN BDR, Kobe', c: 'Japan', co: ['Python', 'R'],
    i: 'Cytoscape automation and access to pathway databases — KEGGscape, py4cytoscape, pywikipathways, transomics2cytoscape. Bioconductor Community Advisory Board and Carpentries-style Bioconductor workshops in Japanese. HUPO PSI mzTab-M working group — a data standard for sharing quantitative mass spectrometry metabolomics results.',
    s: 'Omics data analysis, network biology, Python/R packaging and GitHub, open community-driven teaching and software development',
    m: 'I am not a researcher. I am a Research Software Engineer. If you are interested in an RSE career, check out the RSEAA community.',
    t: ['Metabolomics', 'Visualisation', 'FAIR/Standards', 'Workflows'] },
  { id: 'p53', n: 'Pitiporn Noisagul (Sam)', a: 'CMUTEAM, Chiang Mai University', c: 'Thailand', co: ['R', 'Python', 'Groovy'],
    i: 'From microbiology to bioinformatics and systems biology. Genome study of cancer, pathogens and plants. Recently learned human pangenome graph analysis and is calling structural variants from the graph for diagnosis and prognosis. Microbiome analysis — 16S rRNA and shotgun metagenomics.',
    s: 'Genomics, metagenomics, metabolomics and transcriptomics',
    m: 'I recently learned to fall asleep with the TV on or a podcast playing. Many thanks to DBCLS and the other Japanese teams for helping organize MedHackathon Asia 2025 in Thailand.',
    t: ['Pangenome', 'Microbiology', 'Genomics', 'Variants', 'Metabolomics'] },
  { id: 'p54', n: 'Yoko Okabeppu', a: 'OKBP inc.', c: 'Japan', co: ['Ruby', 'Java', 'Python', 'vibe coding'],
    i: 'RDF for geological data at a deep sea research institute; RDF engineer in bioinformatics since 2011, primarily microbial databases. Founded her own company in 2019. Microbial culture media database; data management of microbial pathway data.',
    s: 'SPARQL and SQL query tuning; designing RDF models',
    m: 'I bought a seafront flat last month and use an RTSP web camera plus wind, wave, tide and weather data to predict the best times for snorkelling — 30 minutes of vibe coding. Next step: I want to catch fish with a spear.',
    t: ['RDF/SPARQL', 'Microbiology', 'Databases'] },
  { id: 'p55', n: 'Satoshi Onoda', a: 'YOHAK LLC', c: 'Japan', co: ['TypeScript', 'HTML/CSS', 'design languages'],
    i: 'Usually develops commercial websites for clients. Joined the TogoMedium project in 2019 as a frontend developer. (Un)official photographer at BH25.',
    s: 'UI / UX / motion programming / photography',
    m: 'Last year an Apple Watch literally saved my life — it found AFib. 15 September is my 42nd birthday.',
    t: ['Web dev', 'Visualisation'] },
  { id: 'p56', n: 'Risa Otsuka', a: 'NITE-NBRC', c: 'Japan', co: ['JavaScript', 'Python', 'Java', 'SQL', 'SPARQL'],
    i: 'Software engineer at NBRC maintaining DBRP, a database about microorganisms, and other project databases. Adding and updating features — wants ideas.',
    s: 'Programming; designing web application architecture; RDF (SPARQL)',
    m: 'I love playing violin and viola in chamber orchestra. I learn Korean. I collect stickers related to the areas where I have attended biohackathons. I would like to hear your stories.',
    t: ['Databases', 'Web dev', 'RDF/SPARQL', 'Microbiology'] },
  { id: 'p57', n: "Eric Gordon Prud'hommeaux", a: 'Unaffiliated', c: 'France', co: ['C++', 'JavaScript', 'TypeScript', 'Java'],
    i: 'Long-time W3C staff, now consulting. Semantic web in health care and life sciences, SPARQL and shapes, XML protocols. Long-ish time at HL7 — V3 (C-CDA), FHIR, FDA therapeutic areas, formal reusable models for clinical trials.',
    s: 'Clinical informatics; RDF and RDF 1.2, SPARQL; RDF data modeling and visualization, usually with ShEx; isomorphic schema and data transformations; grammars and domain-specific languages',
    m: 'My dining room furniture folds against the wall to optimize for skating. I have no silverware organizers. I dig chaos.',
    t: ['RDF/SPARQL', 'Clinical', 'FAIR/Standards', 'Ontologies'] },
  { id: 'p58', n: 'Núria Queralt Rosinach', a: 'LUMC', c: 'Netherlands', co: ['Python', 'Shell', 'SPARQL'],
    i: 'PhD in chemistry then MSc bioinformatics. DisGeNET-RDF for genotype to phenotype integration; BioKnowledge reviewer for KG creation. Interests: building RDF graphs on the fly with DBCLS services, RDF-based patient to clinical trial matching, representing structural and epigenetic variants in RDF, rare disease diagnosis with genAI, and bringing science closer to citizens with an RDF-based app.',
    s: 'RDF, multimodal data modelling, ShEx, OWL ontologies, FAIR ML, fast learner, chatty person',
    m: 'My first BH was in 2015 — my 10th anniversary. I ran my first half marathon this April. Started learning Italian, German and Dutch. I like dragonflies, ladybugs and butterflies.',
    t: ['RDF/SPARQL', 'Rare disease', 'Clinical', 'Knowledge graphs', 'FAIR/Standards'] },
  { id: 'p59', n: 'Apiwat Sangphukieo', a: 'Chiang Mai University', c: 'Thailand', co: ['Python', 'Unix'],
    i: 'Bioinformatician across functional genomics of bacterial genomes, protein structure modelling, untargeted metabolomics pipelines, NGS data processing and GWAS. Interested in blood-based early cancer detection and host-pathogen interaction. Now developing a standard omics platform as a national core facility — genome depository, imputation server, polygenic risk score prediction.',
    s: 'Problem solving, coding, omics data from hospitals',
    m: 'I just adopted 2 Chibas. Then my life changed.',
    t: ['Genomics', 'Metabolomics', 'Clinical', 'Cloud/HPC', 'Machine learning'] },
  { id: 'p60', n: 'Nattawet Sriwichai (Golf)', a: 'Chiang Mai University', c: 'Thailand', co: ['R', 'Python', 'Shell', 'SQL', 'PHP'],
    i: 'Transcriptional regulatory networks of protein coding and miRNA genes in cassava, the MeTRN database, large-scale cassava transcriptomics, microbiome analysis of microbial fuel cells. Now HPC systems administrator at the Faculty of Medicine, CMU, and research omics data catalog.',
    s: 'Omics data analysis, systems biology, network biology, web development',
    m: 'Cat lover. Exploring with passion, guiding with kindness.',
    t: ['Plants/Agriculture', 'Cloud/HPC', 'Web dev', 'Microbiology', 'Databases'] },
  { id: 'p61', n: 'David Steinberg', a: 'Camber, San Francisco', c: 'USA', co: ['Python'],
    i: 'Agentic AI and HPC at cambercloud.com; on2vec for knowledge representation; croissant-rdf bridging biology and ML communities; dockstore.org for reproducible analysis and workflows; GA4GH standards development.',
    s: 'Machine learning/AI/LLM, data modeling and API integration, data visualization, GitHub and release management, project planning and communication',
    m: '1st Biohackathon 2017 Morioka. I was the opener DJ for a Japanese electronic musician earlier this year.',
    t: ['LLM/AI', 'Workflows', 'Cloud/HPC', 'FAIR/Standards', 'Visualisation'] },
  { id: 'p62', n: 'Mark Streer', a: 'SciBite (Elsevier), Cambridge', c: 'UK', co: ['Python'],
    i: 'Senior scientific curator supporting Japanese biopharma companies with integrated platforms for ontology management, biomedical NER, and semantic search/RAG. Veteran Japanese-English translator with 10+ years in biomedical literature and 3 years in manga.',
    s: 'LLM-enhanced pipelines for ontology curation and translation; biomedical ontologies (MeSH, MONDO, ChEMBL, Uberon); API scripting',
    m: 'Former digital nomad and travel bug; give me an excuse to visit you. このハッカソンは、皆さんにとって英語で自分の研究を議論する貴重な機会だと思いますが、今イギリスに住んでいる私にとっても日本語で語り合える絶好のチャンスともなります。',
    t: ['Ontologies', 'Text mining', 'LLM/AI', 'FAIR/Standards'] },
  { id: 'p63', n: 'Chang Sun', a: 'Maastricht University', c: 'Netherlands', co: ['Python', 'JavaScript'],
    i: 'Assistant professor with expertise in AI for healthcare, privacy-preserving health data analysis (federated learning), and personal health knowledge graphs. Current work: using disease ontologies and KGs to enhance generative AI for health and life sciences — rare disease, CVD, diabetes.',
    s: 'Synthetic data generation, privacy-preserving data analysis, health data management, digital consent, personal KG, health ontologies (SNOMED, ORDO, HPO)',
    m: '',
    t: ['Clinical', 'Knowledge graphs', 'LLM/AI', 'Rare disease', 'Machine learning'] },
  { id: 'p64', n: 'Shin-ichiro Tago', a: 'Fujitsu Limited', c: 'Japan', co: ['Prompt', 'Python', 'C', 'Java', 'SPARQL', 'JavaScript', 'Shell'],
    i: 'Now: unlocking the full potential of LLMs as orchestrator. Past: genome explainable AI, knowledge platforms, stream data processing, multiprocessors, graph theory.',
    s: 'Chatting with LLMs, system architecture, coding, a little bit about genomics',
    m: "I'm hosting board game nights, so if you're interested please let me know.",
    t: ['LLM/AI', 'Knowledge graphs', 'Genomics', 'Machine learning'] },
  { id: 'p65', n: 'Toyoyuki Takada', a: 'RIKEN BioResource Research Center', c: 'Japan', co: ['R', 'Python'],
    i: 'Mammalian geneticist specializing in laboratory animal science and mouse genetics; phenotype-genotype connection using mouse models; genome sequencing since the 1990s; created MoG+, a database of genomic variations of Japanese mouse strains. Hopes to gain insights on displaying structural variants from long-read sequencing and their effects on cis-regulatory elements in a database.',
    s: 'New to bioinformatics, but a background in wet-lab research and a user’s perspective on databases',
    m: 'I love fishing.',
    t: ['Variants', 'Genomics', 'Databases', 'Visualisation'] },
  { id: 'p66', n: 'Shoichiro Takahashi', a: 'Trinet Corporation', c: 'Japan', co: ['Python', 'Go', 'C++'],
    i: 'Working on a utilization system for rare disease. TRE/SDE, data sharing and federated analysis.',
    s: 'Coding; system design',
    m: '3rd Dan, Kodokan Judo. I teach judo to children in my town. I have a cauliflower ear and my earphones do not fit.',
    t: ['Rare disease', 'Clinical', 'Cloud/HPC'] },
  { id: 'p67', n: 'Satoshi Tanaka', a: 'Trans-IT Co., Ltd.', c: 'Japan', co: ['Python', 'Java', 'JavaScript', 'PHP', 'C', 'C++'],
    i: 'Mass++ for mass spectrometry data analysis and visualization; jPOST proteome database; GlycoWorkbench glycan analysis tool.',
    s: 'Software development; data science',
    m: 'When I was in elementary school, I lived near the Biohackathon venue.',
    t: ['Proteomics', 'Glycomics', 'Visualisation', 'Databases'] },
  { id: 'p68', n: 'Pumipat Tongyoo (Aun)', a: 'Kasetsart University', c: 'Thailand', co: ['Python', 'R', 'SQL'],
    i: 'PhD in biomedical science analyzing human multi-omics data for genes involved in lupus nephritis; MSc in bioinformatics on Arthrospira operon structure; BSc in agricultural biotechnology. Current research focuses on utilizing biological resources for plant breeding with genomics and bioinformatics as core tools.',
    s: 'Molecular biology and biotechnology; bioinformatics for omics data analysis',
    m: 'This is my first time in Japan. P = G + E + G×E, so life is just ATCG shaped by the environment. Leaving my cats for a whole week.',
    t: ['Plants/Agriculture', 'Genomics', 'Clinical'] },
  { id: 'p69', n: 'Kotaro Uchida', a: 'Hiroshima University', c: 'Japan', co: ['Python'],
    i: "Master's student working on a meta-analysis of human and mouse transcriptome data related to cold exposure, collected from public databases.",
    s: 'Bioinformatics',
    m: "I'm a beginner, but I'll do my best!",
    t: ['Genomics', 'Databases'] },
  { id: 'p70', n: 'Andra Waagmeester', a: 'Amsterdam UMC / Micelio', c: 'Netherlands', co: ['Good question.'],
    i: 'Assistant professor, Reusable Health Data; founder of Micelio working across biodiversity, agriculture and more. Current interests: sheXer, rdf-config, SPARQL examples and SPARQLFest; extending SPARQL-examples with result snippets; rediscovering an undocumented Japanese nocturnal insect.',
    s: 'Championing linked data and FAIR data adoption; SPARQL and ShEx expertise; teacher and communicator',
    m: 'Recently composed a Spanish love song (with GenAI) called grafos de conocimiento. Still believe iNaturalist is the best introduction to linked data. Also a passionate beekeeper.',
    t: ['RDF/SPARQL', 'FAIR/Standards', 'Biodiversity', 'Knowledge graphs', 'Plants/Agriculture'] },
  { id: 'p71', n: 'Chatarin Wangsanuwat (Chad)', a: 'Mahidol University', c: 'Thailand', co: ['Python', 'R'],
    i: 'PhD in chemical engineering focused on next-generation sequencing; R&D in RNA biology and high-throughput mRNA screening; molecular biologist transitioned into medical bioinformatics. Interested in sequencing data analysis and clinical genomic diagnosis.',
    s: 'Molecular biology, RNA biology, NGS/LRS. Can support biological context, data testing, usability feedback, documentation.',
    m: "I'm from Thailand and currently work here after ~13 years in the US. I studied Japanese for 3 semesters plus 2 months in Ishikawa — 10+ years later I forgot all of it.",
    t: ['Genomics', 'Clinical'] },
  { id: 'p72', n: 'Chunlei Wu', a: 'The Scripps Research Institute', c: 'USA', co: ['Python'],
    i: 'Professor at Scripps Research. Lab focuses on biomedical knowledge-graph infrastructure — NIH-NCATS Biomedical Data Translator, BioThings, SmartAPI — and FAIR data sharing and resource discovery: Center for Data2Health, N3C, NIH-NIAID Data Ecosystem.',
    s: 'Knowledge graph integration and interfacing with LLM',
    m: 'Both my wife and I are fans of Studio Ghibli. Just learned there is Ghibli Park near Nagoya.',
    t: ['Knowledge graphs', 'FAIR/Standards', 'LLM/AI', 'Databases'] },
  { id: 'p74', n: 'Issaku Yamada', a: 'The Noguchi Institute', c: 'Japan', co: ['ChatGPT', 'Claude Code'],
    i: 'Organic chemistry until 2006, then glycoscience: databases (GlyTouCan, GlyCosmos, GlycoNAVI), ontologies (GlycoRDF, GlycoCoO), structure representation (WURCS), drawing tools (GlycanBuilder), format converters and structure search.',
    s: 'Organic chemistry, glycoinformatics',
    m: 'The flying rabbit is my mascot. But I like cats and dogs.',
    t: ['Glycomics', 'Ontologies', 'Databases', 'RDF/SPARQL'] },
  { id: 'p75', n: 'Atsuko Yamaguchi', a: 'Tokyo City University', c: 'Japan', co: ['Java', 'C++', 'SPARQL', 'Python', 'SQL'],
    i: 'Graph algorithms for using knowledge graphs; originally mathematics, then theoretical computer science, then bioinformatics. At DBCLS 2007-2020, now visiting professor. Interests: knowledge graphs, large language models, rare diseases, relations between genes and MRI images for lissencephaly, and sports data analysis.',
    s: 'Semantic web technologies; improvement of algorithms; statistical analysis',
    m: 'I love fishing. I go fishing at least twice a year and have never come back empty-handed.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Rare disease'] },
  { id: 'p76', n: 'Sora Yonezawa', a: 'Hiroshima University', c: 'Japan', co: ['Shell', 'Python', 'R', 'CWL'],
    i: 'PhD student utilizing public databases to find understudied genes related to heat stress; currently exploring novel heat stress-responsive lncRNAs using FANTOM data. Interested in constructing analysis workflows.',
    s: 'Omics data analysis; analysis workflow construction with CWL; plant2human workflow',
    m: 'My home prefecture is Iwate.',
    t: ['Workflows', 'Genomics', 'Plants/Agriculture', 'Databases'] },
  { id: 'p77', n: 'Naoya Yoshikuwa', a: 'University of Tokyo', c: 'Japan', co: ['Python'],
    i: "Drug efficacy prediction for cancer using ML until 2024; now a master's student in the Goto lab at DBCLS researching AI agents (LLM) for rare disease.",
    s: 'Programming for data science, ML and LLM, but not so proficient',
    m: 'I like running, so I want to run around the hotel during this event at least once.',
    t: ['LLM/AI', 'Rare disease', 'Machine learning'] },
  { id: 'p78', n: 'Achille Zappa', a: 'GaLSIC, Soka University', c: 'Japan', co: [],
    i: 'Biomedical engineer with a PhD on biomedical semantic data integration, management and knowledge engineering. Ten years at University of Galway (DERI, Insight, Data Science Institute). Core interests: semantic web technologies, data interoperability, multidisciplinary domains, data management and integration, data governance. Now lecturer at Soka University using semantic web technologies to improve glycomics data integration and knowledge discovery. Projects: HGA Human Glycome Atlas TOHSA, GlyCosmos.',
    s: 'Semantic web technologies, data interoperability, data governance, project management',
    m: 'Former W3C AC representative and working group participant.',
    t: ['Glycomics', 'RDF/SPARQL', 'Knowledge graphs', 'FAIR/Standards', 'Ontologies'] }
];
