/* BioHackathon 2026 — participant index.
   Built from the self-introduction deck (data/, git-ignored).
   The deck is the roster: only people with a slide in that export appear here.

   Ids are stable name slugs, not slide numbers: the deck is re-ordered and
   re-numbered between exports, so slide numbers drift. photos.json is keyed by
   the same slug, and scripts/extract-deck.py writes both the portraits and the
   raw slide text (data/people.json) that these entries are curated from.

   Fields: n name, a affiliation, c country, co coding, i interests, s skills,
   m message, t topic tags */
window.BH_SOURCE = {
  deck: 'https://docs.google.com/presentation/d/1UWasNu6Wa_zCRhuWErF0cu2-uHpxwVBOU_6bNarQe1c/edit',
  people: 90,
  portraits: 90
};
window.BH_PEOPLE = [
  { id: 'haruma-abe', n: 'Haruma Abe', a: 'Tokyo City University', c: 'Japan', co: ['Python', 'R'],
    i: "Master's student in computer science: detecting injury patterns in racehorses, and proposing a \"pedigree distance\" for them. Interested in racehorse body analysis and pose estimation, and in AI and databases.",
    s: 'Statistical analysis in Python',
    m: 'Likes football and horse racing.',
    t: ['Population genetics', 'Machine learning'] },
  { id: 'anggi', n: 'Anggi (Angganararas Lungidningtyas)', a: 'Biomedical and Genome Science Initiative (BGSI)', c: 'Indonesia', co: ['Python', 'AWS', 'GCP', 'Claude Code'],
    i: "Bioinformatics lead at BB Binomika, part of BGSI, Indonesia's national whole genome sequencing programme under the Ministry of Health. Recently finished a population-stratified pharmacogenomics analysis of four anti-epileptic drug variants across the full BGSI cohort, and is mapping carrier frequencies for ten ACMG SF actionable gene loci in the same cohort. Also benchmarked MGI against Illumina on 23 dually sequenced samples.",
    s: 'Population genomics and pharmacogenomics; maintaining internal operations and the platform for external researchers and hospitals',
    m: 'First BioHackathon. Happy to talk BGSI, population genomics, or just compare notes on pipeline headaches. Likes cats, sim building games and RPGs.',
    t: ['Population genetics', 'Genomics', 'Variants', 'Clinical'] },
  { id: 'yui-asano', n: 'Yui Asano', a: 'Swallow Design Studio Inc.', c: 'Japan', co: [],
    i: "Visual and UI/UX design. Designed this year's BioHackathon poster.",
    s: 'Visual and UI/UX design',
    m: 'Studied so many citrus family trees for the poster — now a citrus expert.',
    t: ['Visualisation'] },
  { id: 'evan-bolton', n: 'Evan Bolton', a: 'NCBI', c: 'USA', co: ['Perl', 'C++', 'SPARQL', 'SQL'],
    i: 'PubChem and PubChemRDF since 2004. Connecting scientific information between chemical substances, biological targets and diseases. Exploring local LLMs to improve information quality, generate queries from natural language, and work more efficiently.',
    s: 'PubChem, NCBI resources, data integration, standards, RDF, cheminformatics, glycoinformatics, literature and patent informatics, machine readability, linked data, knowledge graphs',
    m: "Come see me and let's chat about your use cases, data needs and wants. How can I help you?",
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Databases', 'FAIR/Standards'] },
  { id: 'hidemasa-bono', n: 'Hidemasa Bono', a: 'Hiroshima University / DBCLS', c: 'Japan', co: ['Shell', 'Perl'],
    i: 'Professor of bioinformatics and genome informatics at Hiroshima University and a member of DBCLS since 2007. Initiator of TogoTV, RefEx and FANTOM, PI for the BioDX centre of innovation (COI-NEXT), and deputy director of the HU Genome Editing Innovation Center. Works on data-driven genome breeding, the data analysis environment for genome editing, and gene function analysis.',
    s: 'Pathway analysis environment development — Quest for Pathways with eXpression (QPX); genome sequencing and analysis',
    m: "Let's decode genomes. Let's democratise the pathway database.",
    t: ['Genomics', 'Databases', 'Plants/Agriculture', 'Visualisation'] },
  { id: 'orion-buske', n: 'Orion Buske', a: 'PhenoTips', c: 'Canada', co: ['Python', 'JavaScript', 'Shell', 'Cursor'],
    i: 'Running a startup building medical genetics software. AI in medical genetics workflows, especially family history and phenotype data. Rare disease diagnosis: ZebraSeek and the Undiagnosed Hackathon. Standards: GA4GH, HPO, Phenopacket. Patient matchmaking — Matchmaker Exchange, PhenomeCentral, semantic similarity between patients.',
    s: 'Entrepreneurship and startups; somewhat rusty full-stack development; loves data analysis and visualization',
    m: 'Highly food-motivated. Loves hiking, canoe camping, foraging mushrooms. Hoping to find matsutake — 松茸を探しています!',
    t: ['Rare disease', 'Clinical', 'FAIR/Standards', 'LLM/AI', 'Visualisation'] },
  { id: 'dawn-chen', n: 'Dawn Chen', a: 'Broad Institute of MIT and Harvard', c: 'USA', co: ['Python', 'R', 'C++', 'JavaScript', 'Claude'],
    i: "By day, develops sequencing, CRISPR and RNA-based tools and builds AI models for genomics and generative sequence design. By night, project lead for BioVault, on privacy-preserving data sharing and open-source genomic analysis tools — with the aim of putting genetic testing and precision medicine within everyone's reach.",
    s: 'Amphibious: ask about anything wetlab and any sequencing assay. Building software and data visualisation; genome engineering, clinical genetics, population genetics; federated data analysis and privacy-enhancing technologies.',
    m: 'Likes science fiction, and organic chemistry — used to do total synthesis.',
    t: ['Genomics', 'Machine learning', 'Clinical', 'Cloud/HPC', 'Variants'] },
  { id: 'jiandong-chen', n: 'Jiandong Chen', a: 'Nagasaki Lab, Kyushu University', c: 'Japan', co: ['Python', 'Rust', 'Claude'],
    i: 'Single-cell RNA-seq analysis (2020–2024), cap analysis of mRNA (2023–2024), and since 2025 developing workflows for combined long-read WGS and methylation analysis, and methods for analysing the structure of variable number tandem repeat regions.',
    s: 'Genome analysis',
    m: 'From 温州 — though the oranges produced there taste different. Sourer.',
    t: ['Genomics', 'Variants', 'Workflows'] },
  { id: 'hirokazu-chiba', n: 'Hirokazu Chiba', a: 'DBCLS', c: 'Japan', co: ['Perl', 'Python', 'JavaScript', 'C'],
    i: 'Comparative genomics across model organisms and ~1,000 bacteria/archaea. Semantic web and graph DBs, Orthology Ontology, SPARQL tooling (spang, formatter), PG format for property graphs, RAG systems over biomedical databases.',
    s: 'RDF, SPARQL, JavaScript, Python',
    m: 'I live near Chiba.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'Ontologies', 'Genomics', 'LLM/AI'] },
  { id: 'hassan-sibroe-abdulla-daanaa', n: 'Hassan Sibroe Abdulla Daanaa', a: 'National Institute of Genetics (NIG)', c: 'Japan', co: ['Python'],
    i: 'Evolutionary genomics — molecular evolution and population genomics. PhD from the Invertebrate Genetics lab at NIG/SOKENDAI, investigating the relationships among protein structural flexibility, architecture and sequence evolution using recent advances in AI. Now a postdoc in the Human Population Genetics lab at NIG.',
    s: 'Molecular evolution; protein structure (IDR) and function; Python-based pipeline development',
    m: 'Likes learning how to learn, and the philosophy of science. Supports Arsenal FC, plays football and will discuss tactics.',
    t: ['Population genetics', 'Genomics', 'Structural biology'] },
  { id: 'michel-dumontier', n: 'Michel Dumontier', a: 'Maastricht University', c: 'Netherlands', co: ['Python', 'Rust', 'agentic coding', 'Claude'],
    i: 'Biochemist by training, data scientist by practice. FAIR data, open science, reproducibility. Ontologies (SIO, SULO, OntoExplorer, RustDL), RDF linked data (Bio2RDF), mapping (ShExMap), metadata (HCLS dataset description, KG metadata). Neurosymbolic AI: biomedical data embedding from molecule to patient, prediction and explainable AI, drug discovery and personalized medicine. Plans: federated agentic research systems — how can researchers with AI meaningfully collaborate? — and temporal knowledge graphs extending SULO with provable temporal transforms.',
    s: 'Ontologies, linked data, data standards, neurosymbolic AI',
    m: 'Temper unbridled enthusiasm with focused effort to give shape to the life you imagine. AI coding: BH-MEET.',
    t: ['Ontologies', 'Knowledge graphs', 'FAIR/Standards', 'LLM/AI', 'Machine learning'] },
  { id: 'danil-ezhov', n: 'Danil Ezhov', a: 'NSS Lab, ITMO University', c: 'Russia', co: ['Python', 'Bash', 'C++', 'Claude'],
    i: 'ML/DL engineer-researcher working on physics-informed neural networks and LLM multi-agent systems; previously a cheminformatics and DL/ML researcher at Syntelly, a Reaxys-like chemical platform. Current projects: PINN-PELINE, an RL agent that builds optimal optimiser chains for training PINNs, and FEDOT.MAS, which generates an optimal multi-agent configuration for a given task.',
    s: 'LLM agents (tool use, structured output, agent loops), RAG; PyTorch, JAX, PEFT fine-tuning, NER; RDKit and genomics data',
    m: 'Did Shotokan karate as a kid (4th kyu). First time abroad, and a second bioinformatics hackathon.',
    t: ['Machine learning', 'LLM/AI', 'Genomics'] },
  { id: 'nuria-fabrega', n: 'Núria Fàbrega', a: 'University of Edinburgh', c: 'UK', co: ['Bash', 'Python', 'Claude'],
    i: 'BSc in chemistry, MSc in bioinformatics, now a second-year PhD student in NLP for biomedicine, working on data reuse by identifying public transcriptomics experiments that are compatible for joint analysis. Interested in everything that improves reuse: LLMs and knowledge graphs for metadata quality, curation, and extraction and standardisation of entities from free text.',
    s: 'Biomedical NLP and LLM-based information extraction; transcriptomics and omics metadata; LLM-assisted data curation and evaluation. Co-developed and taught a tutorial on agentic AI and MCPs for biomedical research.',
    m: 'First BioHackathon, and in Japan. Obsessed with Obsidian and knowledge organisation tools. Loves learning languages and finds Japanese — especially kanji — really fun; a long-standing wish is a research stay in Japan.',
    t: ['LLM/AI', 'Knowledge graphs', 'Text mining', 'FAIR/Standards', 'Databases'] },
  { id: 'takatomo-fujisawa', n: 'Takatomo Fujisawa', a: 'DDBJ (unofficial), BSI, NIG', c: 'Japan', co: ['Perl', 'Ruby', 'SPARQL'],
    i: 'Oversees development and operation of all DDBJ databases and services — assembled sequences, SRA/GEA, BioProject/BioSample, MetaboBank, JGA. Applying AI/LLM to database repositories; advancing the RDF Portal with dynamic ID relationships and tools such as Bio-MCP-blast.',
    s: 'Repository development, database integration, genome annotation, curation',
    m: 'Would like to work on making genome submission easy with AI agents and MCP. Had tai-meshi three times in Matsuyama two years ago.',
    t: ['Databases', 'LLM/AI', 'RDF/SPARQL', 'Genomics', 'FAIR/Standards'] },
  { id: 'kazumichi-fujiwara', n: 'Kazumichi Fujiwara', a: 'National Institute of Genetics (NIG)', c: 'Japan', co: ['Python', 'R', 'Shell'],
    i: 'PhD in information science from Hokkaido (2022), then the Mouse Genomics Resource Lab at NIG (2023–2026) and the Human Population Genomics Lab there since September 2026. Evolutionary and population genomics: population structure, admixture and demographic history; hybridisation, introgression and natural selection; genome evolution and comparative genomics — from wild house mice to flowering cherries.',
    s: 'Genome analysis and bioinformatics; population genomics and phylogenomics; whole-genome sequencing and variant analysis; genome assembly and comparative genomics',
    m: 'A research journey from mice to cherry trees to humans next. For fun, analyses their own genome — about 30× WGS of themselves. First BioHackathon, still figuring things out.',
    t: ['Population genetics', 'Genomics', 'Variants', 'Biodiversity'] },
  { id: 'toyofumi-fujiwara', n: 'Toyofumi Fujiwara', a: 'DBCLS', c: 'Japan', co: [],
    i: 'AI-based diagnostic support tools: DiseaseSearch, PanelSearch, CaseSharing, and ZebraSeek coming soon. Enhancing interoperability between Japanese and international disease resources through NanbyoData, NANDO and Mondo Japanese.',
    s: 'Rare disease data curation and interoperability; biomedical informatics and knowledge representation',
    m: "We will be developing a diagnostic support tool using LLMs, so if you're interested, look for the doll — except I forgot the doll this year.",
    t: ['Rare disease', 'LLM/AI', 'Ontologies', 'Clinical', 'FAIR/Standards'] },
  { id: 'naohisa-goto', n: 'Naohisa Goto', a: 'The University of Osaka', c: 'Japan', co: ['Ruby', 'C', 'C++', 'R', 'Perl', 'PHP', 'Python'],
    i: 'Lecturer in the NGS Core Facility, Bioinformatics Center, Research Institute for Microbial Diseases. Computer system administration, BioRuby since 2001, development of the Ruby language since 2011, genome/metagenome sequence analysis, gene expression analysis.',
    s: 'Programming, bioinformatics data analysis, server/network management. Interested in RDF and CWL.',
    m: 'I like travelling by train.',
    t: ['Genomics', 'Cloud/HPC', 'Workflows', 'Microbiology'] },
  { id: 'susumu-goto', n: 'Susumu Goto', a: 'DBCLS', c: 'Japan', co: ['Perl', 'R'],
    i: 'KEGG and LinkDB at Kyoto University until 2017; since then database integration via knowledge graphs, jPOST proteome database, and NLP/LLM for biological literature mining.',
    s: 'Database integration; proteome data, pathway and reaction data',
    m: 'Mainly in charge of management rather than coding now, but would like to discuss database integration. Member of the male choir Tokyo Lietertafel 1925.',
    t: ['Knowledge graphs', 'Databases', 'Proteomics', 'Text mining', 'LLM/AI'] },
  { id: 'robert-hoehndorf', n: 'Robert Hoehndorf', a: 'KAUST', c: 'Saudi Arabia', co: ['Groovy', 'C', 'C++', 'Aider'],
    i: 'Neuro-symbolic AI and protein function prediction. Phenotype-based variant prioritisation and phenotype ontologies. Causality and causal knowledge graphs. Tools: AberOWL2, mOWL, PhysioMap, DeepGO.',
    s: 'OWL/DL reasoning, ontology embeddings, LLM agents for curation and annotation; knowledge graphs and SPARQL endpoints for biology; large-scale genome annotation. Plans: causal knowledge graphs, agents that reason, and the Flora Phenotype Ontology for plant traits.',
    m: 'Reproduced my research group as agents in Gastown. Loves hiking — Kumano Kodo after the BioHackathon — kitesurfing, fishing and foraging.',
    t: ['Ontologies', 'Knowledge graphs', 'LLM/AI', 'Rare disease', 'Variants'] },
  { id: 'masae-hosoda', n: 'Masae Hosoda', a: 'DBCLS', c: 'Japan', co: ['Python', 'Java', 'Ruby'],
    i: 'Multiple glycan structure alignment (MCAW tool), glycan-glycan binding molecules, Human Glycome Atlas. Linking Japanese intractable and rare disease information with glycan-related data. GlyCosmos: glycan motifs and MCP adoption.',
    s: 'Glycoinformatics. Learning SPARQL and RDF.',
    m: 'I will join the BioHackathon from September 17, as I will be attending a glycoscience conference beforehand.',
    t: ['Glycomics', 'Rare disease', 'RDF/SPARQL', 'Databases'] },
  { id: 'tzung-chien-hsieh', n: 'Tzung-Chien Hsieh', a: 'University Hospital Bonn', c: 'Germany', co: ['Python', 'Ruby'],
    i: 'Computational phenotyping of rare genetic disorders. GestaltMatcher — a deep learning framework for diagnosing rare disorders through facial image analysis — and the GestaltMatcher Database, the global reference for facial phenotypic variability in rare disease, with around 13,000 patients. Extending to brain MRI and fetal ultrasound imaging.',
    s: 'Facial image analysis and computer vision; exome and genomic data analysis; multimodal data integration',
    m: 'Looking for recommendations about Hello Kitty and Tomica.',
    t: ['Rare disease', 'Machine learning', 'Clinical', 'Genomics'] },
  { id: 'shuya-ikeda', n: 'Shuya Ikeda', a: 'DBCLS', c: 'Japan', co: ['awk'],
    i: 'TogoID — ID conversion service for life-science databases. BioSample curation. Improving metadata quality using LLMs.',
    s: 'Database integration (RDF, SPARQL); LLMs',
    m: 'I like spiders. I recently started bird watching.',
    t: ['Databases', 'LLM/AI', 'RDF/SPARQL', 'FAIR/Standards'] },
  { id: 'manabu-ishii', n: 'Manabu Ishii', a: 'Genome Analytics Japan', c: 'Japan', co: ['Z80', 'C', 'C++', 'Python', 'Perl', 'Java', 'JavaScript', 'CWL'],
    i: '20th-century software engineer. This BioHackathon: togoimputation.org imputation server development, and a Trusted Research Environment if possible.',
    s: "I'm interested in coding with LLM and TDD",
    m: 'Visited Edinburgh Castle, a 40-year-old dream — エジンベア from ドラクエ3. Yesterday: Matsuyama Castle.',
    t: ['Databases', 'LLM/AI', 'Clinical', 'Workflows'] },
  { id: 'priscilla-joanne', n: 'Priscilla Joanne', a: 'University of Tokyo', c: 'Japan', co: ['Python', 'SPARQL'],
    i: "Master's student in computational biology, in the Goto lab at DBCLS. Generating question-answer datasets using knowledge graphs from the RDF portal.",
    s: "I'm still new in the field, but in this BioHackathon I want to find practical advice, solidify my Master's topic, and listen to new things about research.",
    m: 'If you like specialty coffee and would like to explore the flavors of Indonesian coffee, contact me — my family runs a coffee business in Indonesia.',
    t: ['Knowledge graphs', 'LLM/AI', 'RDF/SPARQL'] },
  { id: 'mayumi-kamada', n: 'Mayumi Kamada', a: 'Kitasato University / The University of Osaka', c: 'Japan', co: ['Python', 'R', 'Ruby', 'JavaScript'],
    i: 'Genome assembly of Bacillus subtilis natto; clinical genome analysis, especially cancer; the MGeND disease variant database; molecular dynamics on K and Fugaku. Now at Kitasato University School of Frontier Engineering and, since 2025, cross-appointed at the Institute for Protein Research, The University of Osaka, on a data platform for drug discovery. Interests: standardisation and integration of clinical genome data, and classification and interpretation of variants.',
    s: 'Machine learning models and three-dimensional structural analysis to predict the disease relevance of genomic variants; databases for genomic medicine',
    m: 'The happiest thing is drinking a highball.',
    t: ['Variants', 'Clinical', 'Machine learning', 'Structural biology', 'Databases'] },
  { id: 'alex-kanitz', n: 'Alex Kanitz', a: 'University of Basel / Swiss Institute of Bioinformatics', c: 'Switzerland', co: [],
    i: 'Open standards-based data analytics platforms with data and compute federation, AI support, trusted research environments and tokenisation: ELIXIR On-Cloud, BioHackCloud, and the Pacific Analytics Platform (currently down, moving from Australia to Europe). Previously bioinformatics tool and workflow development, mostly transcriptomics, and experimental molecular biology in the distant past.',
    s: 'Web dev, workflows, GA4GH, RO-Crates, DevOps, bits of this and that',
    m: 'A bit disappointed that the opening workshop is not in a beer garden, as the Google Maps link implied. Greetings from the Taipei mountains.',
    t: ['Workflows', 'Cloud/HPC', 'FAIR/Standards', 'Web dev'] },
  { id: 'deepa-kasaragod', n: 'Deepa Kasaragod', a: 'Hiroshima University', c: 'Japan', co: ['Python', 'R'],
    i: "Master's in photonics, PhD in biomedical optics (optical coherence tomography), now assistant professor in neurobiology.",
    s: 'Open-source tool development; microscopy hardware and software; recently started working on omics data',
    m: 'A wannabe drummer. First time at BioHackathon.',
    t: ['Visualisation', 'Machine learning'] },
  { id: 'toshiaki-katayama', n: 'Toshiaki Katayama', a: 'DBCLS / BSI, NIG', c: 'Japan', co: ['Ruby', 'JavaScript', 'SPARQL'],
    i: 'Design & develop open source tools for knowledge graphs and genome graphs. TogoPackage and TogoMCP give AI agents access to local data and public life-science databases. Wants Japan to come together to design its new national bioscience database center.',
    s: 'Facilitates discussions, coding, and drinking :)',
    m: 'Started learning the tenor saxophone this year. Tasted sake from 670+ breweries across Japan — brought 20+ bottles of Ehime local sake.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Databases', 'Genomics'] },
  { id: 'yosuke-kawai', n: 'Yosuke Kawai', a: 'National Institute of Genetics, Mishima / BSI / JIHS', c: 'Japan', co: ['Python', 'R'],
    i: 'Human population genomics and evolution, long-read sequencing, pangenomes and structural variation, genomic medicine and clinical variant resources. Projects: pangenomics, federated variant curation, and a variant database. Recruiting postdocs and graduate students through SOKENDAI in genomics, bioinformatics and population genetics.',
    s: 'Genomic data analysis in the background of population genetics; large-scale analysis of genomic data on cluster computers',
    m: 'I have two cats.',
    t: ['Pangenome', 'Population genetics', 'Variants', 'Genomics', 'Cloud/HPC'] },
  { id: 'shin-kawano', n: 'Shin Kawano', a: 'Kitasato University / DBCLS', c: 'Japan', co: ['Ruby', 'Python', 'R'],
    i: 'Wet molecular biology on acetic acid bacteria at Hokkaido, bioinformatics and glycoinformatics (KEGG GLYCAN) at Kyoto, metabolomics at Takanashi Milk, and now proteomics at DBCLS and Kitasato — the jPOST project, metaproteomics and non-canonical proteomics, AI-driven proteomics and metadata curation.',
    s: 'Bioinformatics, proteomics, biological databases, mass spectrometry',
    m: 'I have an energetic Bichon Frise 🐶',
    t: ['Proteomics', 'Databases', 'Glycomics', 'LLM/AI', 'Metabolomics'] },
  { id: 'shuichi-kawashima', n: 'Shuichi Kawashima', a: 'DBCLS', c: 'Japan', co: ['Ruby'],
    i: 'KEGG, MAGEST, AAindex; Togo* products; RDF portal; TogoMedium and the Growth Medium Ontology. Integration of microorganism-related information.',
    s: 'Data integration, RDF/OWL/SPARQL, data models, web services, triple stores, Ruby, Togo* tools',
    m: 'I visited South Africa for the Biocuration Conference.',
    t: ['RDF/SPARQL', 'Ontologies', 'Databases', 'Microbiology', 'FAIR/Standards'] },
  { id: 'akira-kinjo', n: 'Akira Kinjo', a: 'Anima Machina G.K.', c: 'Japan', co: ['Claude'],
    i: 'Biophysics and bioinformatics. Main developer at Protein Data Bank Japan (2006–2018), maths teacher at Universiti Brunei Darussalam (2018–2024), one-man company since 2024. Now on TogoMCP (a product of BH25 in Mie), an MIE file ablation study and its possible standardisation, and LLMs against life-science databases generally — including when an MCP server beats a skill.',
    s: 'PDB and protein structures; databases (Postgres, RDF/SPARQL)',
    m: 'Came back to BioHackathon last year after seven or eight years away. The bike died on Awaji-shima on the way to BH26, and was resurrected the next day.',
    t: ['Structural biology', 'LLM/AI', 'Databases', 'RDF/SPARQL'] },
  { id: 'yuko-kitano', n: 'Yuko Kitano', a: 'BITS Co., Ltd.', c: 'Japan', co: ['Python'],
    i: 'Bioinformatics engineer and tool developer. Manages a WGS pipeline of about 5,000 human samples a year as a daily Nextflow job. Built an LLM ACMG variant interpreter at MedHackathon Asia in Singapore, now live in the cloud, and a VCF annotation and filtering tool for pre-review analysis — both deployed and ready to try.',
    s: 'Traceability systems for human genome data; Nextflow workflows across ~5,000 individuals a year; pedigree visualisation tools built with AI assistance',
    m: 'Loves their cats, and misses them.',
    t: ['Genomics', 'Workflows', 'Variants', 'Clinical', 'LLM/AI'] },
  { id: 'ruka-kobayashi', n: 'Ruka Kobayashi', a: 'Trinet Corporation', c: 'Japan', co: ['Python'],
    i: 'Web application development and prompt engineering. Built an LLM tool for nursing discharge summaries that uses structured XML output to auto-fill template fields. New to bioinformatics and currently learning it, hoping to explore it hands-on with teammates from the life sciences.',
    s: 'Web application development, prompt engineering',
    m: 'First time at this hackathon, looking forward to working with everyone and absorbing as much as possible.',
    t: ['LLM/AI', 'Web dev', 'Clinical'] },
  { id: 'julia-koblitz', n: 'Julia Koblitz', a: 'Leibniz Institute DSMZ', c: 'Germany', co: ['Python', 'PHP', 'JavaScript', 'SQL', 'MongoDB'],
    i: 'Head of Data Integration at DSMZ Digital Diversity.',
    s: 'Database and web development, data integration (e.g. via RDF), UI/UX and graphic design, artificial intelligence',
    m: 'I built an Ema display at home.',
    t: ['Databases', 'Web dev', 'RDF/SPARQL', 'Microbiology', 'Visualisation'] },
  { id: 'amane-kurata', n: 'Amane Kurata', a: 'Hiroshima University', c: 'Japan', co: ['Python'],
    i: 'Undergraduate developing a machine-learning pipeline for evaluating the safety of genome editing, with a particular focus on allergenicity.',
    s: 'Machine-learning pipelines for genome-editing safety',
    m: 'First time at an event like this. Limited experience in the field so far, and out to make the most of it.',
    t: ['Machine learning', 'Genomics'] },
  { id: 'shuto-machida', n: 'Shuto Machida', a: 'Kyushu University', c: 'Japan', co: ['Python', 'Shell'],
    i: 'Developing haplotype phasing algorithms for the human genome; applying combinatorial optimization to genomic problems. Member of the JoGo project, building high-resolution haplotype reference panels from long-read sequencing data.',
    s: 'Bioinformatics and genome data analysis, combinatorial optimization and graph methods, quantum computing. BioHackathon idea: explore Japanese citrus genomes with AI — compare mikan, iyokan, orange and others at the genome level.',
    m: 'Collaborative researcher at Kyushu University, from Okinawa. Second BioHackathon, and excited to visit Ehime for the first time.',
    t: ['Variants', 'Genomics', 'Pangenome', 'Machine learning', 'Plants/Agriculture'] },
  { id: 'taichi-matsubara', n: 'Taichi Matsubara', a: 'BlueMeme Inc. / Medical Institute of Bioregulation, Kyushu University', c: 'Japan', co: ['Python', 'Claude'],
    i: 'Quantum machine learning for genomics: predicting transcription factor binding from DNA. QTFPred is a quantum–classical learning method for base-resolution TF binding prediction and cooperative motif analysis (Briefings in Bioinformatics 26(6), bbaf604, 2025). Current interests are chromatin accessibility and variant effects, learning from limited data, and interpreting regulatory motifs.',
    s: 'Genomic sequence modelling, deep learning, quantum machine learning and quantum computation, transcription factor and gene regulation',
    m: 'PhD in science, March 2026. Turned thirty yesterday. Has sung in choirs for over ten years, currently a mixed chorus in Fukuoka, and travels.',
    t: ['Machine learning', 'Genomics', 'Variants'] },
  { id: 'miguel-mazumder', n: 'Miguel Mazumder', a: 'GaLSIC, Soka University', c: 'Japan', co: ['MATLAB', 'Python', 'Rust', 'Shell'],
    i: 'Human Glycome Atlas TOHSA — secure full-stack service for biodata with access control, data privacy and interoperability. NIH Common Fund Data Ecosystem: integration of n-triples/XML biomedical data with Neo4j and Cypher. Machine learning workflows and MATLAB image analysis pipelines. Interested in RDF data modeling, SPARQL, glycan data integration and ontology mapping.',
    s: 'Image processing and analysis, machine learning, Docker, NGS data analysis, knowledge graphs, computer vision',
    m: 'I can fall asleep anywhere. This is my first biohackathon and I am relatively new to semantic web technologies, so I hope to learn a lot here.',
    t: ['Glycomics', 'Knowledge graphs', 'Machine learning', 'RDF/SPARQL', 'Web dev'] },
  { id: 'gos-micklem', n: 'Gos Micklem', a: 'DBCLS / University of Cambridge', c: 'UK', co: ['Perl', 'Python', 'C'],
    i: 'PI of the InterMine project — HumanMine and FlyMine. Moving the back end from Postgres to QLever; wants BlueGenes to work on any SPARQL endpoint, e.g. the RDF portal. This time: infer the schema of a QLever endpoint into the InterMine model, and MetaStanza to InterMine.',
    s: 'Large-scale data integration and tools and interfaces for flexible, efficient querying and data visualisation',
    m: 'I metabolise caffeine very slowly and alcohol quite quickly.',
    t: ['Databases', 'RDF/SPARQL', 'Web dev', 'Visualisation', 'Knowledge graphs'] },
  { id: 'mari-t-minowa', n: 'Mari T. Minowa', a: 'DBCLS', c: 'Japan', co: ['???'],
    i: 'Evolution of colicins, expression of human blood factors, promoter analysis of dopamine receptor genes, glycosyl transferases. Launch and operation of the NBDC human database from the ethical and personal-information viewpoint.',
    s: 'Knowledge to take charge of various aspects around the research (public relations, contracts, help desk)',
    m: "I'm still caught up in the Kawagoe festival. Love butterflies and grow many plants. Love dinos.",
    t: ['Databases', 'Clinical', 'Glycomics'] },
  { id: 'hiroyuki-mishima', n: 'Hiroyuki Mishima', a: 'Nagasaki University', c: 'Japan', co: ['Ruby', 'JavaScript', 'Python', 'R'],
    i: 'Assistant professor in rare disease bioinformatics; formerly dentist and post-doc in cleft palate and rare disease genetics. This hackathon: next-generation phenotyping by integrating facial analysis (GestaltMatcher) and HPO-based analysis (PubCaseFinder) to fight the diagnostic odyssey.',
    s: 'Full-stack bioinformatics from server room construction to building diagnostic workflows',
    m: '',
    t: ['Rare disease', 'Clinical', 'Workflows', 'Cloud/HPC'] },
  { id: 'nobutaka-mitsuhashi', n: 'Nobutaka Mitsuhashi', a: 'DBCLS', c: 'Japan', co: ['JavaScript', 'Bash', 'Python', 'CWL'],
    i: 'BodyParts3D; NBDC Human Database and its security guidelines; TogoVar — Japanese genetic variation, allele frequencies, clinical significance, pathogenicity prediction, literature integration, GWAS Catalog, structural variants from JoGo, LD from BioBank Japan.',
    s: 'Data integration through web application development using RDF middleware (SPARQList, Stanza); system administration of DBCLS computational infrastructure',
    m: 'I started using a dietary log app. I realized I was eating too much fat and salt, and not getting enough protein and vitamins. Data visualization is very useful.',
    t: ['Variants', 'Genomics', 'RDF/SPARQL', 'Web dev', 'Cloud/HPC'] },
  { id: 'rajat-kumar-mondal', n: 'Rajat Kumar Mondal', a: 'Soka University, GaLSIC', c: 'Japan', co: ['Python', 'SQL', 'PHP', 'JavaScript'],
    i: "Biological database and tool development against antimicrobial resistance and infectious disease — seven papers and a patent as a master's student, then two years in industry as a senior bioinformatics scientist across digital health, consumer genomics, AI and policy management. Joined Kinoshita's lab at the Glycan and Life Systems Integration Center in July 2026, structuring human data from GlyCosmos for HGA-TOHSA and downstream machine learning. Starts a PhD next year.",
    s: 'Bio-data challenges, open-source development with collaborators, intuitive UI/UX',
    m: 'First-generation graduate, first time in Japan and first time at BioHackathon. Wants to collaboratively develop a unified data resource to combat AMR and infectious disease. New to the semantic web and finds it super complex. Big fan of tempura and rice crackers.',
    t: ['Databases', 'Glycomics', 'Microbiology', 'Machine learning', 'Web dev'] },
  { id: 'yuki-moriya', n: 'Yuki Moriya', a: 'DBCLS / BSI, NIG', c: 'Japan', co: ['JavaScript', 'SPARQL', 'Perl'],
    i: 'Web tools for the semantic web — SPARQL support, Endpoint browser, SPARQList. Data visualization: Protein browser, Haplotype explorer. Data integration: TogoDX/human, Togo*, DIVE. jPOST, LLMs.',
    s: 'SPARQL, SPARQList and TogoStanza',
    m: 'The organizers prepared local sake from Ehime (35 litres) for this BH, with financial support from the local government.',
    t: ['RDF/SPARQL', 'Visualisation', 'Variants', 'Proteomics', 'Web dev'] },
  { id: 'hina-motoyoshi', n: 'Hina Motoyoshi', a: 'Trinet Corporation', c: 'Japan', co: ['Python', 'Terraform', 'Docker'],
    i: 'MSc in life science from Rikkyo on the intracellular localisation of chloroplast proteins. Platform engineer from 2023, joined Trinet in December 2025, and now works with DBCLS on operational improvements. Lately interested in AI guidelines, guardrails and coding frameworks.',
    s: 'Infrastructure as code, cloud-native platform engineering, web application development — Python, Terraform, Docker, Kubernetes, Helm, AWS',
    m: 'First time here and excited to build with everyone. Escape games are the hobby, and local mandarin orange juice is the goal.',
    t: ['Cloud/HPC', 'Web dev', 'LLM/AI'] },
  { id: 'hiroki-muroda', n: 'Hiroki Muroda', a: 'Trinet Corporation', c: 'Japan', co: ['Python', 'JavaScript', 'SQL', 'Shell'],
    i: 'Secure platforms for clinical and genomic data: processing and quality control of clinical data, and secure data management and transfer inside trusted research environments.',
    s: 'Data processing and quality control; web system design and implementation',
    m: 'First time at the international BioHackathon. Enjoys eating, drinking and watching movies, and looking forward to getting to know everyone.',
    t: ['Clinical', 'Genomics', 'Cloud/HPC', 'Web dev'] },
  { id: 'masao-nagasaki-contact-nagasaki-csml-org', n: 'Masao Nagasaki', a: 'Kyushu University, Medical Institute of Bioregulation', c: 'Japan', co: ['Python', 'Shell', 'R', 'SQL', 'PHP', 'agentic coding'],
    i: 'Professor, Division of Biomedical Information Analysis. Bioinformatics, medical informatics, genome biology, large-scale data analysis. Interests: ACTG-haplotype centric human data analysis, tool development and annotation; collaboration on haplotype-based analysis; haplotype-based semi-automatic annotation with database MCP; graph genome and T2T.',
    s: 'Haplotype analysis, tool development, annotation, large-scale data analysis',
    m: 'Post-doctoral and student positions available.',
    t: ['Variants', 'Pangenome', 'Genomics', 'Cloud/HPC', 'LLM/AI'] },
  { id: 'takeru-nakazato', n: 'Takeru Nakazato', a: 'NITE Biological Resource Center (NBRC)', c: 'Japan', co: ['Perl', 'Python'],
    i: 'NBRC provides bacteria and fungi as a bioresource center. POMIC — a catalog of microorganisms that utilize CO2. Interested in linking data across microbial culture collections and databases.',
    s: 'Databases; NGS and gene expression analysis; biodiversity informatics and DNA barcoding',
    m: "Member of the biodiversity information standards body TDWG — GBIF, BOLD, Catalogue of Life. Andra is running this year's bioblitz project on iNaturalist. Loves butterflies and beetles, and visited a haiku bar last night.",
    t: ['Microbiology', 'Databases', 'Biodiversity', 'FAIR/Standards'] },
  { id: 'claude-nanjo', n: 'Claude Nanjo', a: 'University of Utah', c: 'USA', co: ['Java', 'Python', 'Kotlin', 'Rust'],
    i: 'Medical informatician focusing on clinical knowledge representation and applications of AI in medicine. Many years in health IT interoperability; HL7 CIMI and LHS co-chair. Currently focused on structured knowledge in agentic AI to improve clinical accuracy — agentic RAG using knowledge graphs, and fetching relevant patient data deterministically.',
    s: 'I would be very interested in how you leverage structured knowledge and deterministic workflows in your agentic AI.',
    m: 'My goal is to swim over 1,000 km this year.',
    t: ['Clinical', 'Knowledge graphs', 'LLM/AI', 'FAIR/Standards', 'Ontologies'] },
  { id: 'russell-neches', n: 'Russell Neches', a: 'Kyoto University', c: 'Japan', co: ['Python', 'C'],
    i: '',
    s: '',
    m: 'Open source, open data, open science, open hardware — open all the things! Goal for the year: justify spending on fancy pens and inks. This is my second Biohackathon. I am on my fourth attempt to pass the driver license practical test.',
    t: ['Microbiology', 'Biodiversity'] },
  { id: 'kozo-nishida', n: 'Kozo Nishida', a: 'RIKEN BDR, Kobe', c: 'Japan', co: ['Python', 'R'],
    i: 'Cytoscape automation and access to pathway databases — KEGGscape, py4cytoscape, pywikipathways, transomics2cytoscape. Bioconductor Community Advisory Board and Carpentries-style Bioconductor workshops in Japanese. HUPO PSI mzTab-M working group — a data standard for sharing quantitative mass spectrometry metabolomics results.',
    s: 'Omics data analysis, network biology, Python/R packaging and GitHub, open community-driven teaching and software development',
    m: 'I am not a researcher. I am a Research Software Engineer. If you are interested in an RSE career, check out the RSEAA community.',
    t: ['Metabolomics', 'Visualisation', 'FAIR/Standards', 'Workflows'] },
  { id: 'pitiporn-noisagul', n: 'Pitiporn Noisagul (Sam)', a: 'CMUTEAM, Chiang Mai University', c: 'Thailand', co: ['R', 'Python', 'Groovy'],
    i: 'From microbiology to bioinformatics and systems biology. Omics study of non-communicable disease, cancer, parasites and Drosophila. Recently learned human pangenome graph analysis and is calling structural variants from the graph for diagnosis and prognosis. Implementing a federated data-sharing framework on FAIR principles within DHARA, the Diabetes Health Analytics and Multi-Omics Research Alliance in Thailand.',
    s: 'Genomics, metagenomics, metabolomics and transcriptomics',
    m: "We accomplished a new ultra-secret quest yesterday. Feeling like I'm losing my coding skills after agentic AI.",
    t: ['Pangenome', 'Microbiology', 'Genomics', 'Variants', 'Metabolomics'] },
  { id: 'ryo-nozu', n: 'Ryo Nozu', a: 'Hiroshima University', c: 'Japan', co: ['Shell'],
    i: 'Comparative genomics and gene regulation in non-model organisms. Developing a pathway analysis platform and extending pathway knowledge beyond model species; recent work on pangenome analysis of a small set of rice varieties.',
    s: 'Genome assembly, gene annotation and comparative genomics; connecting biological questions with sequencing data analysis',
    m: 'Some of the animals worked with are much bigger than they are — past projects have included whale sharks and manta rays.',
    t: ['Genomics', 'Pangenome', 'Plants/Agriculture', 'Biodiversity'] },
  { id: 'naoya-oec', n: 'Naoya Oec', a: 'Dogrun inc', c: 'Japan', co: ['Python'],
    i: 'Develops metabolic pathway visualisation apps that run on Jupyter, along with other data visualisation and exploration tools.',
    s: 'Data visualisation, brewing coffee, and 3D modelling in collaboration with AI agents',
    m: 'Building visual, exploratory tools for pathway data.',
    t: ['Visualisation', 'Metabolomics'] },
  { id: 'soichi-ogishima', n: 'Soichi Ogishima', a: 'ToMMo, Tohoku University', c: 'Japan', co: ['Python', 'Perl', 'R'],
    i: 'Integration of genome, exposome and clinical data for the Tohoku Medical Megabank, a prospective genome cohort of 150,000 people — phenotyping, and ML/AI for disease risk prediction. Standardisation across ISO/TC215/SC1, GA4GH, HL7 and the IMIA health informatics working group, and designing a learning health system in genomic medicine through consensus building and policy recommendation.',
    s: 'Population cohort data integration and analysis; phenotyping; ML/AI for disease risk prediction',
    m: 'Craft beer lover — Ise Kadoya is one of the most renowned craft beer breweries in Japan. Veteran of BH18, BH23 and BH24.',
    t: ['Clinical', 'Genomics', 'Machine learning', 'FAIR/Standards', 'Databases'] },
  { id: 'tazro-ohta-and-macoto-ohta', n: 'Tazro Ohta', a: 'Chiba University', c: 'Japan', co: ['Claude Code', 'GPT Astra'],
    i: 'Omics database with Shinya and Zaonan (Kumamoto), LLM-assisted data curation with Shuya (DBCLS), Workflow-as-a-Service and workflow security risk assessment with Sator, Asian Biobank Assemble with friends across Asia, helping MedHackathon Asia and planning the 2027 edition, and federated GWAS with AI agents.',
    s: 'Maco makes small troubles; Taz solves small troubles.',
    m: "This week Taz will: discuss anything with you, ask things of the agents, play with Maco, check the agents' progress, repeat. The slide is now shared with Macoto, aged five.",
    t: ['Workflows', 'LLM/AI', 'Databases', 'Cloud/HPC', 'FAIR/Standards'] },
  { id: 'yoko-okabeppu', n: 'Yoko Okabeppu', a: 'OKBP inc.', c: 'Japan', co: ['Ruby', 'Java', 'Python', 'vibe coding'],
    i: 'Database engineer at the Deep Sea Research Institute (2004–2008), investigating RDF for geological data, then an RDF database engineer in bioinformatics since 2011, mostly building microbial databases. Founded her own company in 2019, a microbial culture media database in 2020, and microbial pathway data management since 2023.',
    s: 'SPARQL and SQL query tuning, designing RDF models, QLever against Virtuoso, microbial metabolism',
    m: 'I bought a seafront flat last month and use an RTSP web camera plus wind, wave, tide and weather data to predict the best times for snorkelling — 30 minutes of vibe coding. Next step: I want to catch fish with a spear.',
    t: ['RDF/SPARQL', 'Microbiology', 'Databases'] },
  { id: 'teppei-okazaki', n: 'Teppei Okazaki', a: 'Tokyo City University', c: 'Japan', co: ['Python', 'C', 'C#', 'Codex'],
    i: "Master's student in computer science, implementing a biomedical literature summarisation system with RAG. Interning at an AI startup, mostly improving AI output and user experience. Interested in AI-related systems and products, and prompt engineering.",
    s: 'LLM engineering; data processing in Python',
    m: 'I used to make money by playing video games.',
    t: ['LLM/AI', 'Rare disease', 'Databases', 'RDF/SPARQL'] },
  { id: 'satoshi-onoda', n: 'Satoshi Onoda', a: 'YOHAK LLC', c: 'Japan', co: ['TypeScript', 'HTML/CSS', 'design languages'],
    i: 'Usually develops commercial websites for clients. Joined the TogoMedium project in 2019 as a frontend developer. (Un)official photographer at BH25.',
    s: 'UI / UX / motion programming / photography',
    m: 'Last year an Apple Watch literally saved my life — it found AFib. 15 September is my 42nd birthday.',
    t: ['Web dev', 'Visualisation'] },
  { id: 'risa-otsuka', n: 'Risa Otsuka', a: 'NITE-NBRC', c: 'Japan', co: ['JavaScript', 'Python', 'Java', 'SQL', 'SPARQL'],
    i: 'Software engineer at NBRC maintaining DBRP, a database about microorganisms, and other project databases. Adding and updating features — wants ideas.',
    s: 'Programming; designing web application architecture; RDF (SPARQL)',
    m: 'I love playing violin and viola in chamber orchestra. I learn Korean. I collect stickers related to the areas where I have attended biohackathons. I would like to hear your stories.',
    t: ['Databases', 'Web dev', 'RDF/SPARQL', 'Microbiology'] },
  { id: 'daniel-puthawala', n: 'Daniel Puthawala', a: "Nationwide Children's Hospital", c: 'USA', co: ['Python', 'LaTeX'],
    i: 'GA4GH product co-lead within the Genomic Knowledge Workstream. Cat-VRS, used to represent and reason about sets of genomic variants; bioinformatics tool and software development mostly in cancer research and variant analysis — the VICC variant normalizer, VICC MetaKB, CIViC and DGIdb. The PhD was in sentence processing, mixing formal theory, experimental psychology and computational modelling.',
    s: 'Balancing formal rigour and practical engineering; graphical design for science communication and outreach; negotiation and building consensus',
    m: 'Spent a year at Tsukuba-Dai and a couple more in southern Ibaraki before starting graduate school in the US. Loves playing and designing board games and TTRPGs.',
    t: ['Variants', 'FAIR/Standards', 'Knowledge graphs', 'Clinical'] },
  { id: 'ashanti-robinson', n: 'Ashanti Robinson', a: 'Soka University', c: 'Japan', co: ['Python'],
    i: "Master's in food science on glycolytic enzymes from infant-associated gut microbiota, then analytical chemist and small-time data wrangler at a food tech startup in San Francisco. Now works remotely with the Kinoshita lab managing structured data for the Human Glycome Atlas knowledge base. Here to learn about the semantic web and RDF tooling, and to see what the BioHackathon community is curious about.",
    s: 'Glycobiology — protein chemistry and enzymology',
    m: 'Occasionally sings for fun, and has just started knitting and crocheting — thoroughly addicted.',
    t: ['Glycomics', 'Microbiology', 'Databases', 'RDF/SPARQL'] },
  { id: 'nuria-queralt-rosinach', n: 'Núria Queralt Rosinach', a: 'LUMC', c: 'Netherlands', co: ['Python', 'Shell', 'SPARQL'],
    i: 'PhD in chemistry then MSc bioinformatics. DisGeNET-RDF for genotype to phenotype integration; BioKnowledge reviewer for KG creation. Interests: building RDF graphs on the fly with DBCLS services, RDF-based patient to clinical trial matching, representing structural and epigenetic variants in RDF, rare disease diagnosis with genAI, and bringing science closer to citizens with an RDF-based app.',
    s: 'RDF, multimodal data modelling, ShEx, OWL ontologies, FAIR ML, fast learner, chatty person',
    m: 'Full eclipse.',
    t: ['RDF/SPARQL', 'Rare disease', 'Clinical', 'Knowledge graphs', 'FAIR/Standards'] },
  { id: 'mkkm-chipo-ruhwode', n: 'Mkkm Chipo Ruhwode', a: 'Kitasato University, Faculty of Frontier Engineering', c: 'Japan', co: [],
    i: 'Graduated at the University of Zimbabwe in 2023 with an undergraduate degree in Statistics; research student at Kyoto University in 2025; now a first-year Master’s student in bioinformatics at Kitasato University. Interests: bioinformatics, breast cancer research, and the application of computer science to medical data.',
    s: 'Statistics. Interested in coding. Since it is my first time here, I am looking forward to gaining practical skills in integrating biological datasets that I can apply to my breast cancer research.',
    m: 'I am an easy going person, I enjoy interacting with people. I knit very well if I am not lazy about it.',
    t: ['Machine learning', 'Clinical', 'Genomics'] },
  { id: 'rutharra', n: 'Rutharra (Ruth)', a: 'National Cancer Centre', c: 'Singapore', co: [],
    i: 'Master of genome analytics and a BSc in genomics and bioinformatics from Monash. Variant scientist at NCCS Singapore and biocurator for the VWD VCEP at ClinGen.',
    s: 'Variant analysis end to end — prioritisation, curation, reporting; data integration, database use, platform and tool improvement; ACMG guidelines. Not a coder, but has tried R and Python.',
    m: 'First time visiting Japan. Loves travelling, animals and learning new languages.',
    t: ['Variants', 'Clinical', 'Databases', 'FAIR/Standards'] },
  { id: 'keiko-sakuma', n: 'Keiko Sakuma', a: 'DBCLS', c: 'Japan', co: [],
    i: 'Research support staff; TogoTV support.',
    s: "I'm at the help desk with Mari, Saori and Masae. If you have any questions or problems, please contact the help desk.",
    m: 'No changes from BH25, but get older :) I like 🍵🧘🎾',
    t: ['Databases'] },
  { id: 'apiwat-sangphukieo', n: 'Apiwat Sangphukieo', a: 'Chiang Mai University', c: 'Thailand', co: ['Python', 'Unix'],
    i: 'A bioinformatician across many kinds of project: functional genomics of bacterial genomes, protein structure modelling, mass-spectrometry pipelines for untargeted metabolomics, NGS processing, genome-wide association analysis. Interested in cancer research — blood-based early detection, genetic susceptibility, and host-pathogen interaction in cancer progression.',
    s: 'Problem solving, coding, omics data from hospitals',
    m: 'I just adopted 2 Chibas. Then my life changed.',
    t: ['Genomics', 'Metabolomics', 'Clinical', 'Cloud/HPC', 'Machine learning'] },
  { id: 'daisuke-satoh', n: 'Daisuke Satoh', a: 'Kamonohashi Inc.', c: 'Japan', co: ['Ruby', 'Rust', 'awk', 'Shell'],
    i: 'Software engineering and web application backends: TogoVar, TogoDX, YummyData (UmakaData) and the RDF Portal, plus Namahage, a VCF validator.',
    s: 'Developing tools; faster processing of large data',
    m: 'Has visited Ehime many times — sightseeing, the Ohenro pilgrimage, and business trips.',
    t: ['Variants', 'RDF/SPARQL', 'Databases', 'Web dev'] },
  { id: 'nattawet-sriwichai', n: 'Nattawet Sriwichai (Golf)', a: 'Chiang Mai University', c: 'Thailand', co: ['R', 'Python', 'Shell', 'SQL', 'PHP'],
    i: 'Center for Agricultural Systems Biology at KMUTT: transcriptional regulatory networks of protein-coding and miRNA genes in cassava, the MeTRN database, large-scale cassava transcriptomics, and microbiome analysis of microbial fuel cells. Now HPC systems administrator at the Faculty of Medicine, CMU, working on the Thai Omics Catalog and an omics data support platform.',
    s: 'Omics data analysis, systems biology, network biology, web development',
    m: 'Cat lover. Exploring with passion, guiding with kindness.',
    t: ['Plants/Agriculture', 'Cloud/HPC', 'Web dev', 'Microbiology', 'Databases'] },
  { id: 'chang-sun', n: 'Chang Sun', a: 'Maastricht University', c: 'Netherlands', co: ['Claude'],
    i: 'Assistant professor with expertise in AI for healthcare, privacy-preserving health data analysis (federated learning), and personal health knowledge graphs. Current work: longitudinal patient records, causal treatment-effect models for rare disease treatment, and using disease ontologies and knowledge graphs to enhance generative AI — LLMs, GANs, diffusion models — for health and life sciences, across rare disease (leukaemia), CVD and diabetes.',
    s: 'Synthetic data generation, privacy-preserving data analysis, health data management, digital consent, personal KG, health ontologies (SNOMED, ORDO, HPO)',
    m: '',
    t: ['Clinical', 'Knowledge graphs', 'LLM/AI', 'Rare disease', 'Machine learning'] },
  { id: 'francis-tablizo', n: 'Francis Tablizo', a: 'Philippine Genome Center, University of the Philippines System', c: 'Philippines', co: ['Python', 'R', 'Shell'],
    i: 'Molecular biology, omics and bioinformatics, clinical genomics, biodiversity and conservation, marine natural products, analysis workflow automation, and machine and deep learning.',
    s: 'Design and implementation of data analysis workflows; data visualisation and interpretation',
    m: 'First BioHackathon, from the Philippines. Not a social media user at all — no Facebook, X or Instagram. Likes watching anime.',
    t: ['Genomics', 'Workflows', 'Clinical', 'Biodiversity', 'Machine learning'] },
  { id: 'shin-ichiro-tago', n: 'Shin-ichiro Tago', a: 'Fujitsu Limited', c: 'Japan', co: ['Prompt', 'Python', 'C', 'Java', 'SPARQL', 'JavaScript', 'Shell'],
    i: 'Now: unlocking the full potential of LLMs as orchestrator. Past: genome explainable AI, knowledge platforms, stream data processing, multiprocessors, graph theory.',
    s: 'Chatting with LLMs, system architecture, coding, a little bit about genomics',
    m: "I'm hosting board game nights, so if you're interested please let me know.",
    t: ['LLM/AI', 'Knowledge graphs', 'Genomics', 'Machine learning'] },
  { id: 'tomohiro-taguchi', n: 'Tomohiro Taguchi', a: 'Hiroshima University', c: 'Japan', co: ['Python'],
    i: 'Studies RuBisCO evolution using bioinformatics, focusing on comparative sequence and phylogenetic analysis of photosynthesis-related genes.',
    s: 'Biological database searches, sequence analysis, phylogenetic analysis, Python data processing',
    m: 'Looking forward to meeting everyone and to the chance to learn from them.',
    t: ['Genomics', 'Plants/Agriculture'] },
  { id: 'shoichiro-takahashi', n: 'Shoichiro Takahashi', a: 'Trinet Corporation', c: 'Japan', co: ['Python', 'Go', 'C++'],
    i: 'Working on a utilization system for rare disease. TRE/SDE, data sharing and federated analysis.',
    s: 'Coding; system design',
    m: '3rd Dan, Kodokan Judo. I teach judo to children in my town. I have a cauliflower ear and my earphones do not fit.',
    t: ['Rare disease', 'Clinical', 'Cloud/HPC'] },
  { id: 'yushi-takahashi', n: 'Yushi Takahashi', a: 'Medical AI Center, Niigata University School of Medicine', c: 'Japan', co: ['TypeScript', 'Python', 'Scala', 'SQL', 'Claude'],
    i: 'PhD in glycoinformatics from Soka University, working on glycan-related repository development — GlyComb for glycoconjugate data, GlycoPOST for glycomics MS raw data, and UniCarb-DR for identification results. At Niigata, MS raw data repositories across several omics fields: jPOST for the proteome, GlycoPOST for the glycome and MB-POST for the metabolome.',
    s: 'Database and data repository development; glycoinformatics; software development',
    m: 'First time at the international BioHackathon. An enthusiast of functional programming languages — Haskell, Scala, F#.',
    t: ['Glycomics', 'Proteomics', 'Metabolomics', 'Databases', 'FAIR/Standards'] },
  { id: 'keitaro-takaoki', n: 'Keitaro Takaoki', a: 'Tokyo City University', c: 'Japan', co: ['Python', 'C', 'R', 'Claude Code', 'Codex'],
    i: "Master's student in computer science, interested in sport — football especially — and in how data and AI can be used to understand human behaviour and performance. Interests: AI and data science, and sports analytics.",
    s: 'Data analysis and processing; LLMs and reinforcement learning',
    m: 'I like football!!',
    t: ['Machine learning', 'LLM/AI'] },
  { id: 'terue-takatsuki', n: 'Terue Takatsuki', a: 'Independent', c: 'USA', co: ['SPARQL', 'Shell'],
    i: 'RIKEN BRC (2009–2017) on the BioResource phenotype database, then DBCLS (2019–2026) on the NANDO/NanbyoData rare-disease ontology and data integration, the Life Science Dictionary, and Japanese localisation of ontologies and biomedical terminology including MP and MONDO.',
    s: 'Data curation and quality control; connecting biological data, terminology and databases',
    m: 'Finally got a visa and moved to the US, and is joining BioHackathon as a participant this year. Still finding a way in the new life there, and glad to be back in Japan for a while. First thing in Matsuyama was mikan juice tasting — Setoka was the favourite.',
    t: ['Rare disease', 'Ontologies', 'Databases', 'FAIR/Standards'] },
  { id: 'satoshi-tanaka', n: 'Satoshi Tanaka', a: 'Trans-IT Co., Ltd.', c: 'Japan', co: ['Python', 'Java', 'JavaScript', 'PHP', 'C', 'C++'],
    i: 'Mass++ for mass spectrometry data analysis and visualization; jPOST proteome database; GlycoWorkbench glycan analysis tool.',
    s: 'Software development; data science',
    m: 'Whenever I visit Ehime I make sure to eat jakoten. I arrived last night and have already had it three times. You should try it.',
    t: ['Proteomics', 'Glycomics', 'Visualisation', 'Databases'] },
  { id: 'haruka-tanimoto', n: 'Haruka Tanimoto', a: 'Hiroshima University', c: 'Japan', co: ['Shell'],
    i: 'Originally plant physiology and energy metabolism, now plant genome analysis at a bioinformatics startup across a broad range of data analysis projects.',
    s: 'Biological interpretation and evaluation of pathway diagrams, particularly from a plant physiology perspective; new member of the QPX project',
    m: 'Taking a first step from being a user of bioinformatics tools toward becoming a contributor, and hoping to learn how others develop tools and contribute to the community.',
    t: ['Plants/Agriculture', 'Genomics'] },
  { id: 'yasuhiro-tanizawa', n: 'Yasuhiro Tanizawa', a: 'CSRS, RIKEN / BSI (DDBJ), NIG', c: 'Japan', co: ['Python', 'JavaScript', 'Rust'],
    i: 'MarpolBase, the Marchantia (liverwort) genome database for a new-generation model plant, and the move from genome database to knowledge base. Genome submission to DDBJ: DFAST for annotation and submission, GGS for unannotated genomes, MARKit for taxonomic marker genes, and an AI agent for submission — file conversion, validation and metadata curation.',
    s: 'Genome annotation and databases; DDBJ/INSDC, GFF, data submission',
    m: '2023 Shizuoka Masters bodybuilding champion.',
    t: ['Genomics', 'Databases', 'Plants/Agriculture', 'LLM/AI', 'FAIR/Standards'] },
  { id: 'nishad-thalhath', n: 'Nishad Thalhath', a: 'RIKEN IMS', c: 'Japan', co: [],
    i: 'Familiar with semantic web technologies, with some experience in social informatics and related fields. Maintains bffo.org, the Bio File Formats and Ontology, and wants to improve its coverage during the hackathon — anomalies and missing formats welcome.',
    s: 'Semantic web technologies; file format ontologies',
    m: 'Says he cannot understand most of the bioinformatics discussed here, and is present to learn.',
    t: ['Ontologies', 'FAIR/Standards', 'RDF/SPARQL'] },
  { id: 'felix-vaura', n: 'Felix Vaura', a: 'University of Tokyo / University of Helsinki', c: 'Japan', co: ['R', 'Claude'],
    i: 'BA in mathematics (2015), MD PhD (2023). Uses statistical genetics to tackle human disease, with a main interest in large-scale pharmacogenomic discovery.',
    s: 'Hands-on with large medical datasets — FinnGen 500k, UK Biobank 500k, BioBank Japan 270k; medication data harmonisation',
    m: 'Training for a first marathon, and played a first chess tournament. Reads and writes fiction. 日本語OK, puhun suomea.',
    t: ['Population genetics', 'Clinical', 'Genomics', 'Variants'] },
  { id: 'vijay-venkatesh', n: 'Vijay Venkatesh', a: 'European Bioinformatics Institute', c: 'UK', co: ['Java', 'Python'],
    i: 'Main developer for identifiers.org and the DocBot project. Built DocBot, an EMBL-wide documentation assistant, and has worked in LLMs and RAG for a while; background in Java, Python, ML and a bit of Android development.',
    s: 'Full-stack web development; RAG and agentic AI development',
    m: 'Originally from a quieter part of India (Kerala), living and working in Cambridge for three years. Travelling across Japan with their wife for a couple of weeks after the hackathon — recommendations dearly welcome.',
    t: ['LLM/AI', 'Web dev', 'FAIR/Standards', 'Databases'] },
  { id: 'ran-wei', n: 'Ran WEI', a: 'Japan Institute for Health Security (JIHS)', c: 'Japan', co: ['Python', 'R', 'C++', 'Ruby', 'ChatGPT', 'Claude'],
    i: 'Rare variant analysis using short-read sequencing data, with a focus on autism-related genetic variation. Cohort-scale genome assembly and pangenome construction for population genomics research. Gut microbiome research on associations with host phenotypes and human genetic variation.',
    s: 'Genome assembly; pangenome graph construction and analysis; short-read and long-read sequencing data analysis; gut microbiome and metagenomic analysis; population-scale genomic data analysis',
    m: 'My son said he will be very happy to be left alone for a week. No souvenir needed, just go.',
    t: ['Variants', 'Pangenome', 'Genomics', 'Microbiology', 'Population genetics'] },
  { id: 'issaku-yamada', n: 'Issaku Yamada', a: 'The Noguchi Institute', c: 'Japan', co: ['ChatGPT', 'Claude Code'],
    i: 'Organic chemistry until 2006, then glycoscience: databases (GlyTouCan, GlyCosmos, GlycoNAVI), ontologies (GlycoRDF, GlycoCoO), structure representation (WURCS), drawing tools (GlycanBuilder), format converters and structure search.',
    s: 'Organic chemistry, glycoinformatics',
    m: 'The flying rabbit is my mascot. But I like cats and dogs.',
    t: ['Glycomics', 'Ontologies', 'Databases', 'RDF/SPARQL'] },
  { id: 'atsuko-yamaguchi', n: 'Atsuko Yamaguchi', a: 'Tokyo City University', c: 'Japan', co: ['Java', 'C++', 'SPARQL', 'Python', 'SQL'],
    i: 'Graph algorithms for using knowledge graphs; originally mathematics, then theoretical computer science, then bioinformatics. At DBCLS 2007-2020, now visiting professor. Interests: knowledge graphs, large language models, rare diseases, relations between genes and MRI images for lissencephaly, and sports data analysis.',
    s: 'Semantic web technologies; improvement of algorithms; statistical analysis',
    m: 'I love fishing. I go fishing at least twice a year and have never come back empty-handed.',
    t: ['Knowledge graphs', 'RDF/SPARQL', 'LLM/AI', 'Rare disease'] },
  { id: 'yasunori-yamamoto', n: 'Yasunori Yamamoto', a: 'DBCLS', c: 'Japan', co: ['Perl', 'Python', 'Java', 'SPARQL', 'JavaScript', 'C#'],
    i: 'Services related to literature — Allie, inMeXes. Semantic web / AI: TogoMCP, Umaka-YummyData, Umaka Viewer, JSON2LD Mapper, RDF-doctor, TogoPics. Plans: making RDF data more reliable and connectable; extracting accession numbers from literature.',
    s: 'Anything to do with LLMs, RDF, OWL, ShEx, SPARQL and MCP. Current interest is managing data quality and MCP for databases. Plans: making RDF data more reliable, connectable and interpretable, and extracting database accession numbers from the literature.',
    m: 'I love onsen / spa. Taking a long walk. Walking with a dog.',
    t: ['RDF/SPARQL', 'LLM/AI', 'Text mining', 'FAIR/Standards', 'Ontologies'] },
  { id: 'naoya-yoshikuwa', n: 'Naoya Yoshikuwa', a: 'University of Tokyo', c: 'Japan', co: ['Python'],
    i: "Drug efficacy prediction for cancer using ML until 2024; now a master's student in the Goto lab at DBCLS researching AI agents (LLM) for rare disease.",
    s: 'Programming for data science, ML and LLM, but not so proficient',
    m: 'Mostly vibe coding with Codex lately, which has me doubting my own programming skills. Tips for AI-agent coding welcome.',
    t: ['LLM/AI', 'Rare disease', 'Machine learning'] },
  { id: 'akiyasu-c-yoshizawa', n: 'Akiyasu C. Yoshizawa', a: 'Niigata University', c: 'Japan', co: ['Perl'],
    i: 'Once an experimental biophysicist in membrane biology, then bioinformatics at Kyoto University and AIST — comparative genomics of eukaryotic intracellular transport, and assembling in-house sequence databases. Mass spectrometry at the University of Tokushima and Shimadzu. Now one of the developers of jPOST, a proteome raw data repository, and MB-POST, a metabolome repository in the Shin-MassBank project, mainly developing analysis and statistical methods and preparing metadata.',
    s: 'Bioinformatics and sequence analysis, mass spectrometry for proteomics, metadata construction mainly in mass-spec fields, biological databases',
    m: 'It has been an incredibly long time — seven years, in fact — since the last BioHackathon.',
    t: ['Proteomics', 'Metabolomics', 'Databases', 'Genomics'] }
];
